const zones=[
 {id:'papa',name:'파파존'}, {id:'outdoor',name:'야외석'},
 {id:'annex',name:'별관'}, {id:'room',name:'별관룸'}
];
const master=[
 {id:'papa-2',zone:'papa',name:'2인석',capacity:2},{id:'papa-bar4',zone:'papa',name:'4인 바테이블',capacity:4},
 {id:'outdoor-1',zone:'outdoor',name:'야외석 1번',capacity:4},{id:'outdoor-2',zone:'outdoor',name:'야외석 2번',capacity:4},{id:'outdoor-3',zone:'outdoor',name:'야외석 3번',capacity:4},{id:'outdoor-4',zone:'outdoor',name:'야외석 4번',capacity:4},
 {id:'annex-1',zone:'annex',name:'별관 1번',capacity:2},{id:'annex-2',zone:'annex',name:'별관 2번',capacity:4},{id:'annex-3',zone:'annex',name:'별관 3번',capacity:4},{id:'annex-4',zone:'annex',name:'별관 4번',capacity:2},
 {id:'room-1',zone:'room',name:'룸테이블 1',capacity:4},{id:'room-2',zone:'room',name:'룸테이블 2',capacity:4},{id:'room-3',zone:'room',name:'룸테이블 3',capacity:4}
];
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));
const jsArg=value=>JSON.stringify(String(value??'')).replace(/</g,'\\u003c');
const statusNames={empty:'사용가능',held:'주문중',occupied:'사용중'};
let docs={};let waitDocs=[];
function toDate(value){if(!value)return null;if(typeof value.toDate==='function')return value.toDate();const d=new Date(value);return Number.isNaN(d.getTime())?null:d;}
function normalizedSeatStatus(status){return status==='held'?'held':status==='occupied'?'occupied':'empty'}
function seatData(s){const remote=docs[s.id]||{};return {...s,...remote,status:normalizedSeatStatus(remote.status)};}
function elapsed(ts){const d=toDate(ts);if(!d)return '';const min=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));return min<60?`${min}분`:`${Math.floor(min/60)}시간 ${min%60}분`;}
async function updateSeat(id,status,extra={}){const s=master.find(x=>x.id===id);if(!s)return;const safeStatus=normalizedSeatStatus(status),clear=safeStatus==='empty';await db.collection('seats').doc(id).set({status:safeStatus,zone:s.zone,name:s.name,capacity:s.capacity,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),...(safeStatus==='occupied'?{occupiedAt:firebase.firestore.FieldValue.serverTimestamp()}:{}),...(clear?{partySize:null,groupSize:null,groupId:null,groupLabel:null,groupTableCount:null,orderId:null,orderNo:null,heldBy:null,heldAt:null,heldUntil:null,occupiedAt:null,cleaningAt:null,reservationName:null,reservationPartySize:null,reservationAt:null,reservationPhone:null}:{}),...extra},{merge:true});}
function reservationForm(s){const existing=docs[s.id]||{};const dt=toDate(existing.reservationAt);const defaultDate=dt?new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16):'';const name=prompt(`${s.name} 예약자명`,existing.reservationName||'');if(name===null)return null;const people=prompt('예약 인원',existing.reservationPartySize||Math.min(s.capacity,2));if(people===null)return null;const time=prompt('예약 일시 (예: 2026-07-16 18:30)',defaultDate.replace('T',' '));if(time===null)return null;const phone=prompt('전화번호 (선택)',existing.reservationPhone||'');if(phone===null)return null;const parsed=new Date(time.replace(' ','T'));if(Number.isNaN(parsed.getTime())){alert('예약 일시를 정확히 입력해 주세요.');return null;}return {reservationName:name.trim(),reservationPartySize:Number(people||0),reservationAt:firebase.firestore.Timestamp.fromDate(parsed),reservationPhone:phone.trim()};}
async function manageSeat(id){const base=master.find(x=>x.id===id),s=seatData(base);if(s.status==='occupied'){if(confirm(`${s.name}을 사용가능으로 변경하시겠습니까?`))await updateSeat(id,'empty');return;}if(s.status==='held'){if(confirm(`${s.name}의 주문중 상태를 해제하시겠습니까?`))await updateSeat(id,'empty');return;}if(confirm(`${s.name}을 사용중으로 변경하시겠습니까?`))await updateSeat(id,'occupied');}
async function bulkAction(){const targets=master.map(seatData).filter(s=>['occupied','held'].includes(s.status));if(!targets.length)return alert('해제할 좌석이 없습니다.');if(!confirm(`${targets.length}개 좌석을 사용가능으로 변경하시겠습니까?`))return;await Promise.all(targets.map(s=>updateSeat(s.id,'empty')));}
function render(){const all=master.map(seatData),count=st=>all.filter(s=>s.status===st).length;document.getElementById('seatSummary').innerHTML=`<span class="empty">사용가능 ${count('empty')}</span><span class="held">주문중 ${count('held')}</span><span class="occupied">사용중 ${count('occupied')}</span><button class="bulk-clean-button start" onclick="bulkAction()">전체 해제</button>`;document.getElementById('seatAdmin').innerHTML=zones.map(z=>`<section class="simple-zone"><h2>${z.name}</h2><div class="simple-seat-grid">${all.filter(s=>s.zone===z.id).map(s=>{const time=s.status==='occupied'?elapsed(s.occupiedAt):s.status==='held'?elapsed(s.heldAt):'';const hint=s.status==='empty'?'터치하면 사용중':s.status==='held'?'터치해서 주문중 해제':'터치해서 사용가능';const waiting=waitDocs.filter(w=>w.seatId===s.id&&w.status==='waiting').length;return `<button class="simple-seat ${s.status}" onclick="manageSeat(${jsArg(s.id)})"><strong>${s.name}</strong><span>최대 ${s.capacity}인</span><em>${statusNames[s.status]}</em>${time?`<small>${time}</small>`:''}${waiting?`<b>줄서기 ${waiting}팀</b>`:''}<small>${hint}</small></button>`;}).join('')}</div></section>`).join('');}
window.manageSeat=manageSeat;window.touchSeat=manageSeat;window.bulkAction=bulkAction;
firebase.auth().onAuthStateChanged(async user=>{try{if(!user)throw new Error('login');const token=await user.getIdTokenResult(true);if(token.claims.admin!==true)throw new Error('admin');document.body.classList.add('admin-unlocked');}catch(e){await firebase.auth().signOut().catch(()=>{});if(window.top===window)location.replace('../admin/');}});
db.collection('seats').onSnapshot(snap=>{docs={};snap.forEach(d=>docs[d.id]=d.data());const badge=document.getElementById('seatConnection');badge.textContent='실시간 연결';badge.className='connection live';render();},e=>{document.getElementById('seatConnection').textContent='연결 오류';alert(e.message);});

db.collection('waitlist').onSnapshot(snap=>{waitDocs=snap.docs.map(d=>({id:d.id,...d.data()}));render()});
setInterval(render,30000);
