const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const assert=require('node:assert/strict');
const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,getDocs,collection,setDoc,updateDoc,deleteDoc,runTransaction,serverTimestamp,Timestamp}=require('firebase/firestore');
const ops=require('../admin-operations.js');

const enabled=Boolean(process.env.FIRESTORE_EMULATOR_HOST);
if(!enabled)test('reservation transition audit rules matrix',{skip:true},()=>{});else{
 let env,admin,adminTwo,user;
 test.before(async()=>{env=await initializeTestEnvironment({projectId:'demo-reservation-transition-audit',firestore:{rules:fs.readFileSync(path.resolve(__dirname,'../firestore.rules'),'utf8')}});admin=env.authenticatedContext('admin-one',{admin:true}).firestore();adminTwo=env.authenticatedContext('admin-two',{admin:true}).firestore();user=env.authenticatedContext('user',{}).firestore()});
 test.beforeEach(()=>env.clearFirestore());test.after(()=>env.cleanup());
 const wrap=(db,ref)=>({native:ref,path:ref.path,collection:name=>({doc:id=>wrap(db,doc(db,ref.path,name,id))})});
 const compat=(db,writes=[])=>({collection:name=>({doc:id=>wrap(db,doc(db,name,id))}),runTransaction:callback=>runTransaction(db,tx=>callback({get:ref=>tx.get(ref.native).then(snapshot=>({exists:snapshot.exists(),data:()=>snapshot.data()})),update(ref,data){writes.push({type:'update',path:ref.path});tx.update(ref.native,data)},set(ref,data,options){writes.push({type:'set',path:ref.path});tx.set(ref.native,data,options)},delete(ref){writes.push({type:'delete',path:ref.path});tx.delete(ref.native)}}))});
 const pickup=Timestamp.fromMillis(2_000_000),prep=Timestamp.fromMillis(1_100_000),lifecycle=id=>`reservation_${id}_${pickup.toMillis()}`;
 const auditContext=(source,uid='admin-one')=>({transitionSource:source,transactionStartedAt:Timestamp.fromMillis(1),clientInstanceId:'emulator-client',appVersion:'admin-v49.1.0',actorRole:'admin',adminId:uid});
 const baseOrder=(id,status='reservation_pending',extra={})=>({storeId:'pangyo2-techno-valley',orderNo:'P1000',customerNumber:'P1000',orderType:'takeout',businessDay:'2026-08-19',pickup:{mode:'reserve',time:'18:30',pickupAt:pickup},status,reservationPaymentType:'pay_on_pickup',reservationLifecycleEnabled:true,reservationLifecycleId:lifecycle(id),reservationPrepStartAt:prep,updatedAt:Timestamp.fromMillis(1),...extra});
 const display=(id,status='cooking')=>({orderNumber:'P1000',displayStatus:status,storeId:'pangyo2-techno-valley',businessDay:'2026-08-19',reservationOrder:true,pickupAt:pickup,reservationPaymentType:'pay_on_pickup',reservationLifecycleId:lifecycle(id),updatedAt:Timestamp.fromMillis(1)});
 async function seed(id,status='reservation_pending',extra={}){await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();await setDoc(doc(db,'orders',id),baseOrder(id,status,extra));if(['cooking','ready'].includes(status))await setDoc(doc(db,'publicOrderDisplays',id),display(id,status==='ready'?'ready':'cooking'))})}
 const readOrder=id=>getDoc(doc(admin,'orders',id)).then(snapshot=>snapshot.data());
 const audits=id=>getDocs(collection(admin,'orders',id,'lifecycleAudit')).then(snapshot=>snapshot.docs.map(item=>item.data()));
 const advance=(db,id,status,source='reservation_timer',overrides={})=>ops.advanceReservationLifecycleTransaction({db:compat(db,overrides.writes||[]),orderId:id,expectedLifecycleId:overrides.lifecycleId||lifecycle(id),expectedPickupAt:overrides.pickupAt||pickup,nowMillis:overrides.nowMillis??(status==='reservation_pending'?prep.toMillis():pickup.toMillis()),serverTimestamp,resolveBusinessDay:()=> '2026-08-19',...auditContext(source,overrides.uid||'admin-one')});

 test('A-D. reservation timer and catch-up write one atomic audit at T-15 and pickup',async()=>{for(const [index,source] of ['reservation_timer','reservation_catch_up'].entries()){const id=`boundary-${index}`;await seed(id);const cookingWrites=[];const cooking=await advance(admin,id,'reservation_pending',source,{writes:cookingWrites});assert.deepEqual([cooking.orderWrites,cooking.displayWrites,cooking.auditWrites,cooking.seatWrites,cooking.paymentCalls],[1,1,1,0,0]);assert.equal(cookingWrites.filter(write=>write.path.includes('lifecycleAudit')).length,1);const readyWrites=[];const ready=await advance(admin,id,'cooking',source,{writes:readyWrites});assert.deepEqual([ready.orderWrites,ready.displayWrites,ready.auditWrites,ready.seatWrites,ready.paymentCalls],[1,1,1,0,0]);const entries=await audits(id);assert.deepEqual(entries.map(entry=>entry.transitionSource),[source,source]);assert.equal((await readOrder(id)).lastTransitionSource,source)}});

 test('E-F. administrator manual ready, pickup and cancel use explicit sources',async()=>{const id='manual';await seed(id,'cooking',{preparationMinutes:15,preparationStartedAt:prep,readyDueAt:pickup,autoReadyEnabled:false});const ready=await ops.completeTakeoutTransaction({db:compat(admin),orderId:id,expectedStatus:'cooking',serverTimestamp,resolveBusinessDay:()=> '2026-08-19',...auditContext('admin_manual_ready')});assert.deepEqual([ready.orderWrites,ready.displayWrites,ready.auditWrites,ready.seatWrites,ready.paymentCalls],[1,1,1,0,0]);const completed=await ops.completeTakeoutPickupTransaction({db:compat(admin),orderId:id,expectedStatus:'ready',serverTimestamp,...auditContext('admin_manual_pickup')});assert.deepEqual([completed.orderWrites,completed.displayDeletes,completed.auditWrites,completed.seatWrites,completed.paymentCalls],[1,1,1,0,0]);assert.deepEqual((await audits(id)).map(entry=>entry.transitionSource),['admin_manual_ready','admin_manual_pickup']);const cancelId='manual-cancel';await seed(cancelId,'cooking',{preparationMinutes:15,preparationStartedAt:prep,readyDueAt:pickup,autoReadyEnabled:false});const cancelled=await ops.cancelAuditedTakeoutTransaction({db:compat(admin),orderId:cancelId,expectedStatus:'cooking',serverTimestamp,...auditContext('admin_manual_cancel')});assert.deepEqual([cancelled.orderWrites,cancelled.displayDeletes,cancelled.auditWrites,cancelled.seatWrites,cancelled.paymentCalls],[1,1,1,0,0]);assert.equal((await audits(cancelId))[0].transitionSource,'admin_manual_cancel')});

 test('G-H,Q. automatic/manual and two-admin races record only the first successful source',async()=>{for(const [id,calls] of [['auto-manual',()=>Promise.allSettled([advance(admin,'auto-manual','cooking','reservation_timer'),ops.completeTakeoutTransaction({db:compat(adminTwo),orderId:'auto-manual',expectedStatus:'cooking',serverTimestamp,resolveBusinessDay:()=> '2026-08-19',...auditContext('admin_manual_ready','admin-two')})])],['two-admin',()=>Promise.allSettled([advance(admin,'two-admin','cooking','reservation_timer'),advance(adminTwo,'two-admin','cooking','reservation_timer',{uid:'admin-two'})])]]){await seed(id,'cooking',{preparationMinutes:15,preparationStartedAt:prep,readyDueAt:pickup,autoReadyEnabled:false});const results=await calls();assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal((await audits(id)).length,1);await assert.rejects(()=>advance(admin,id,'cooking','reservation_timer'));assert.equal((await audits(id)).length,1)}});

 test('I-K,P. stale lifecycle, pickup, deadline and state mismatch commit zero writes',async()=>{const id='guarded';await seed(id);for(const overrides of [{lifecycleId:'stale'},{pickupAt:Timestamp.fromMillis(3)},{nowMillis:prep.toMillis()-1}]){const writes=[];await assert.rejects(()=>advance(admin,id,'reservation_pending','reservation_timer',{...overrides,writes}));assert.equal(writes.length,0)}await env.withSecurityRulesDisabled(async context=>updateDoc(doc(context.firestore(),'orders',id),{status:'completed'}));const writes=[];await assert.rejects(()=>advance(admin,id,'reservation_pending','reservation_timer',{writes}));assert.equal(writes.length,0);assert.equal((await audits(id)).length,0)});

 test('L-O. audit is admin-readable, append-only, transaction-bound and rejects PII',async()=>{const id='rules';await seed(id);await advance(admin,id,'reservation_pending','reservation_timer');const auditId=`${lifecycle(id)}__reservation_pending__cooking`,auditRef=doc(admin,'orders',id,'lifecycleAudit',auditId);assert.equal((await getDoc(auditRef)).exists(),true);await assertFails(getDoc(doc(user,'orders',id,'lifecycleAudit',auditId)));await assertFails(getDocs(collection(user,'orders',id,'lifecycleAudit')));await assertFails(updateDoc(auditRef,{appVersion:'changed'}));await assertFails(deleteDoc(auditRef));const saved=(await getDoc(auditRef)).data();await assertFails(setDoc(doc(admin,'orders',id,'lifecycleAudit','standalone'),saved));await assertFails(setDoc(doc(admin,'orders',id,'lifecycleAudit','pii'),{...saved,phoneLast4:'1234'}));await assertFails(setDoc(doc(user,'orders',id,'lifecycleAudit','user'),saved))});

 test('R-T. normal takeout auto-ready keeps public display atomic with one audit and no seat/payment writes',async()=>{const id='regular';await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();await setDoc(doc(db,'orders',id),{storeId:'pangyo2-techno-valley',orderNo:'P1001',customerNumber:'P1001',orderType:'takeout',businessDay:'2026-08-19',pickup:{mode:'now'},status:'cooking',preparationMinutes:15,preparationStartedAt:prep,readyDueAt:pickup,autoReadyEnabled:true,updatedAt:Timestamp.fromMillis(1)});await setDoc(doc(db,'publicOrderDisplays',id),{orderNumber:'P1001',displayStatus:'cooking',storeId:'pangyo2-techno-valley',businessDay:'2026-08-19',preparationMinutes:15,preparationStartedAt:prep,readyDueAt:pickup,autoReadyEnabled:true,updatedAt:Timestamp.fromMillis(1)})});const writes=[],result=await ops.autoCompleteTakeoutTransaction({db:compat(admin,writes),orderId:id,expectedReadyDueAt:pickup,expectedPreparationStartedAt:prep,nowMillis:pickup.toMillis(),serverTimestamp,resolveBusinessDay:()=> '2026-08-19',...auditContext('takeout_auto_retry')});assert.deepEqual([result.orderWrites,result.displayWrites,result.auditWrites,result.seatWrites,result.paymentCalls],[1,1,1,0,0]);assert.equal(writes.length,3);assert.equal((await getDoc(doc(admin,'publicOrderDisplays',id))).data().displayStatus,'ready');assert.equal((await audits(id))[0].transitionSource,'takeout_auto_retry')});
}
