const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,runTransaction,serverTimestamp,setDoc,updateDoc}=require('firebase/firestore');
const {transitionAdminSeatState}=require('../admin-operations');
const PROJECT_ID='demo-admin-unified-seat-state';
if(!process.env.FIRESTORE_EMULATOR_HOST)test('admin unified seat production helper rules matrix',{skip:'run with Firestore emulator'},()=>{});
else{
 let env;test.before(async()=>{env=await initializeTestEnvironment({projectId:PROJECT_ID,firestore:{rules:fs.readFileSync(path.join(__dirname,'..','firestore.rules'),'utf8')}})});test.after(async()=>env.cleanup());
 const admin=uid=>env.authenticatedContext(uid,{admin:true}).firestore(),user=uid=>env.authenticatedContext(uid,{}).firestore();
 const compat=db=>({collection:name=>({doc:id=>doc(db,name,id)}),runTransaction:callback=>runTransaction(db,tx=>callback({get:async ref=>{const snap=await tx.get(ref);return {exists:snap.exists(),data:()=>snap.data()}},set:(...args)=>tx.set(...args)}))});
 async function seed(id,data){await env.withSecurityRulesDisabled(ctx=>setDoc(doc(ctx.firestore(),'seats',id),data))}
 async function read(id){return (await getDoc(doc(admin('reader'),'seats',id))).data()}
 async function transition(db,id,from,to){return transitionAdminSeatState({db:compat(db),seatId:id,expectedStatus:from,targetStatus:to,serverTimestamp,supportedSeatIds:['papa-2','papa-bar4']})}
 test('all five allowed transitions use the production helper and one seat write',async()=>{for(const [from,to] of [['empty','occupied'],['empty','reserved'],['occupied','empty'],['reserved','occupied'],['reserved','empty']]){await seed('papa-2',{status:from,orderId:null});const result=await transition(admin(`${from}-${to}`),'papa-2',from,to);assert.equal((await read('papa-2')).status,to);assert.equal(result.seatWrites,1);assert.equal(result.orderWrites,0);assert.equal(result.publicOrderDisplayWrites,0);assert.equal(result.paymentCalls,0)}});
 test('held sources reject every target with zero writes and preserve lease fields',async()=>{const held={status:'held',heldBy:'customer',heldAt:new Date(1),heldUntil:new Date(Date.now()+60000),partySize:3,orderId:null};for(const target of ['occupied','reserved','empty']){await seed('papa-2',held);await assert.rejects(transition(admin(`held-${target}`),'papa-2','held',target),error=>error.code==='seat/invalid-transition');const after=await read('papa-2');assert.equal(after.status,'held');assert.equal(after.heldBy,'customer');assert.equal(after.partySize,3);assert.equal(after.orderId,null)}});
 test('unknown, order-linked, missing, and stale requests have no partial writes',async()=>{await seed('papa-2',{status:'mystery',marker:1});await assert.rejects(transition(admin('unknown'),'papa-2','unknown','empty'));assert.equal((await read('papa-2')).marker,1);await seed('papa-2',{status:'empty',orderId:'order-1',marker:2});await assert.rejects(transition(admin('linked'),'papa-2','empty','reserved'));assert.equal((await read('papa-2')).marker,2);await env.withSecurityRulesDisabled(ctx=>ctx.firestore()._delegate?Promise.resolve():Promise.resolve());await assert.rejects(transition(admin('missing'),'papa-bar4','empty','reserved'),error=>error.code==='seat/not-found');await seed('papa-2',{status:'reserved',marker:3});await assert.rejects(transition(admin('stale'),'papa-2','empty','occupied'));assert.equal((await read('papa-2')).marker,3)});
 test('two admins racing from the same source produce exactly one success',async()=>{await seed('papa-2',{status:'empty',orderId:null});const results=await Promise.allSettled([transition(admin('a'),'papa-2','empty','reserved'),transition(admin('b'),'papa-2','empty','occupied')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);assert.ok(['reserved','occupied'].includes((await read('papa-2')).status))});
 test('customer hold and admin transition race produces one winner without correction writes',async()=>{await seed('papa-2',{status:'empty',orderId:null});const customer=user('customer'),ref=doc(customer,'seats','papa-2');const hold=runTransaction(customer,async tx=>{const snap=await tx.get(ref);if(snap.data().status!=='empty')throw new Error('STALE');tx.update(ref,{status:'held',heldBy:'customer',heldAt:serverTimestamp(),heldUntil:new Date(Date.now()+60000),updatedAt:serverTimestamp()})});const results=await Promise.allSettled([hold,transition(admin('admin-race'),'papa-2','empty','reserved')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.ok(['held','reserved'].includes((await read('papa-2')).status))});
 test('non-admin direct admin-state mutation is denied',async()=>{await seed('papa-2',{status:'empty',orderId:null});await assertFails(updateDoc(doc(user('not-admin'),'seats','papa-2'),{status:'reserved',reservedBy:'admin'}));assert.equal((await read('papa-2')).status,'empty')});
}
