const test=require('node:test');
const assert=require('node:assert/strict');
const ops=require('../admin-operations.js');

const ts=millis=>({toMillis:()=>millis});
function harness(initial){
 const docs=new Map([['orders/r1',{...initial}]]),writes=[];
 const ref=path=>({path,collection:name=>({doc:id=>ref(`${path}/${name}/${id}`)})});
 const db={collection:name=>({doc:id=>ref(`${name}/${id}`)}),runTransaction:async callback=>callback({get:async ref=>({exists:docs.has(ref.path),data:()=>docs.get(ref.path)}),update(ref,data){writes.push({type:'update',path:ref.path,data});docs.set(ref.path,{...docs.get(ref.path),...data})},set(ref,data){writes.push({type:'set',path:ref.path,data});docs.set(ref.path,{...docs.get(ref.path),...data})},delete(ref){writes.push({type:'delete',path:ref.path});docs.delete(ref.path)}})};
 return {db,docs,writes};
}
const base=pickup=>({orderType:'takeout',status:'payment_pending',pickup:{mode:'reserve',time:'18:30',pickupAt:ts(pickup)},orderNo:'R100',customerNumber:'1000',storeId:'pangyo2-techno-valley',businessDay:'2026-08-19',language:'ko',customerIdentityType:'phone_last4'});
const args=h=>({db:h.db,orderId:'r1',serverTimestamp:()=>ts(999),timestampFromMillis:ts,adminId:'admin-1',transitionSource:'reservation_timer',transactionStartedAt:ts(998),clientInstanceId:'client-1',appVersion:'admin-test',actorRole:'admin'});

test('reservation selection writes only the order and preserves canonical pickup timestamp',async()=>{const pickup=2_000_000,h=harness(base(pickup));const result=await ops.startReservationLifecycleTransaction({...args(h),paymentType:'pay_on_pickup',expectedPickupAt:ts(pickup)});assert.equal(result.orderWrites,1);assert.equal(result.displayWrites,0);assert.equal(result.seatWrites,0);assert.equal(result.paymentCalls,0);assert.equal(h.writes.length,1);const order=h.docs.get('orders/r1');assert.equal(order.status,'reservation_pending');assert.equal(order.reservationPaymentType,'pay_on_pickup');assert.equal(order.reservationPrepStartAt.toMillis(),pickup-15*60*1000);assert.equal(order.pickup.pickupAt.toMillis(),pickup)});

test('T-15 boundary atomically starts cooking and publishes one reservation display and audit',async()=>{const pickup=2_000_000,h=harness({...base(pickup),status:'reservation_pending',reservationPaymentType:'prepaid',reservationLifecycleEnabled:true,reservationLifecycleId:'life-1',reservationPrepStartAt:ts(pickup-900000)});await assert.rejects(()=>ops.advanceReservationLifecycleTransaction({...args(h),expectedLifecycleId:'life-1',expectedPickupAt:ts(pickup),nowMillis:pickup-900001,resolveBusinessDay:o=>o.businessDay}),{code:'order/deadline-pending'});assert.equal(h.writes.length,0);const result=await ops.advanceReservationLifecycleTransaction({...args(h),expectedLifecycleId:'life-1',expectedPickupAt:ts(pickup),nowMillis:pickup-900000,resolveBusinessDay:o=>o.businessDay});assert.deepEqual([result.status,result.orderWrites,result.displayWrites,result.auditWrites,result.seatWrites,result.paymentCalls],['cooking',1,1,1,0,0]);assert.equal(h.docs.get('publicOrderDisplays/r1').displayStatus,'cooking');const audit=h.docs.get('orders/r1/lifecycleAudit/life-1__reservation_pending__cooking');assert.equal(audit.transitionSource,'reservation_timer');assert.equal(audit.actorUid,'admin-1');assert.equal(h.docs.get('orders/r1').lastTransitionSource,'reservation_timer')});

test('pickup boundary atomically marks ready without changing pay-on-pickup state',async()=>{const pickup=2_000_000,h=harness({...base(pickup),status:'cooking',reservationPaymentType:'pay_on_pickup',reservationLifecycleEnabled:true,reservationLifecycleId:'life-1',reservationPrepStartAt:ts(pickup-900000),preparationStartedAt:ts(pickup-900000),readyDueAt:ts(pickup)});await assert.rejects(()=>ops.advanceReservationLifecycleTransaction({...args(h),expectedLifecycleId:'life-1',expectedPickupAt:ts(pickup),nowMillis:pickup-1,resolveBusinessDay:o=>o.businessDay}),{code:'order/deadline-pending'});assert.equal(h.writes.length,0);const result=await ops.advanceReservationLifecycleTransaction({...args(h),transitionSource:'reservation_catch_up',expectedLifecycleId:'life-1',expectedPickupAt:ts(pickup),nowMillis:pickup,resolveBusinessDay:o=>o.businessDay});assert.equal(result.status,'ready');assert.equal(h.docs.get('orders/r1').reservationPaymentType,'pay_on_pickup');assert.equal(h.docs.get('publicOrderDisplays/r1').displayStatus,'ready');assert.equal(h.docs.get('orders/r1/lifecycleAudit/life-1__cooking__ready').transitionSource,'reservation_catch_up')});

test('stale pickup, lifecycle identity, non-reservation and completed orders perform zero writes',async()=>{for(const mutate of [o=>o.pickup.pickupAt=ts(3),o=>o.reservationLifecycleId='changed',o=>o.orderType='dinein',o=>o.status='completed']){const pickup=2_000_000,order={...base(pickup),pickup:{...base(pickup).pickup},status:'reservation_pending',reservationPaymentType:'prepaid',reservationLifecycleEnabled:true,reservationLifecycleId:'life-1',reservationPrepStartAt:ts(pickup-900000)};mutate(order);const h=harness(order);await assert.rejects(()=>ops.advanceReservationLifecycleTransaction({...args(h),expectedLifecycleId:'life-1',expectedPickupAt:ts(pickup),nowMillis:pickup,resolveBusinessDay:o=>o.businessDay}));assert.equal(h.writes.length,0)}});

test('coordinator keeps one timer per order and replaces stale identities',()=>{let current={id:'r1',...base(2000000),status:'reservation_pending',reservationPaymentType:'prepaid',reservationLifecycleEnabled:true,reservationLifecycleId:'a',reservationPrepStartAt:ts(1100000)},next=1;const timers=new Map(),cleared=[];const coordinator=ops.createReservationLifecycleCoordinator({execute:async()=>{},getCurrentOrder:()=>current,now:()=>0,setTimer:(fn,delay)=>{const id=next++;timers.set(id,{fn,delay});return id},clearTimer:id=>{cleared.push(id);timers.delete(id)}});coordinator.reconcile([current]);coordinator.reconcile([current]);assert.equal(coordinator.timers.size,1);current={...current,reservationLifecycleId:'b'};coordinator.reconcile([current]);assert.equal(coordinator.timers.size,1);assert.equal(cleared.length,1);coordinator.cancel('r1');assert.equal(coordinator.timers.size,0)});
