const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const assert=require('node:assert/strict');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc,runTransaction,serverTimestamp,Timestamp}=require('firebase/firestore');
const ops=require('../admin-operations.js');
const enabled=Boolean(process.env.FIRESTORE_EMULATOR_HOST);
if(!enabled)test('reservation lifecycle rules matrix',{skip:true},()=>{});else{
 let env,admin,user,kiosk;
 test.before(async()=>{env=await initializeTestEnvironment({projectId:'demo-reservation-lifecycle',firestore:{rules:fs.readFileSync(path.resolve(__dirname,'../firestore.rules'),'utf8')}});admin=env.authenticatedContext('admin-one',{admin:true}).firestore();user=env.authenticatedContext('user',{}).firestore();kiosk=env.authenticatedContext('kiosk-one',{role:'kiosk',storeId:'pangyo2-techno-valley',kioskId:'mobile-01'}).firestore()});
 test.beforeEach(()=>env.clearFirestore());test.after(()=>env.cleanup());
 const compat=(db,writes=[])=>({collection:name=>({doc:id=>doc(db,name,id)}),runTransaction:callback=>runTransaction(db,tx=>callback({get:ref=>tx.get(ref).then(s=>({exists:s.exists(),data:()=>s.data()})),update(ref,data){writes.push(ref.path);tx.update(ref,data)},set(ref,data,options){writes.push(ref.path);tx.set(ref,data,options)},delete(ref){writes.push(ref.path);tx.delete(ref)}}))});
 const payload=pickup=>({channel:'mobile',deviceId:'mobile-01',appVersion:'test',schemaVersion:2,aggregationVersion:1,storeId:'pangyo2-techno-valley',storeName:'판교2테크노밸리점',orderNo:'P1000',customerNumber:'P1000',phone:'01012345678',phoneMasked:'010-****-5678',phoneLast4:'5678',language:'ko',customerIdentityType:'phone_last4',orderType:'takeout',partySize:null,seat:null,pickup:{mode:'reserve',time:'18:30',pickupAt:pickup},disposables:false,items:[{id:'P001',qty:1,total:10000}],itemCount:1,normalAmount:10000,discountAmount:0,totalAmount:10000,total:10000,benefit:'normal',payment:{method:'card'},status:'payment_pending',recommendationEvents:[],createdAt:serverTimestamp(),createdAtClient:'2026-08-19T00:00:00.000Z',source:'test'});
 const read=async(name,id)=>(await getDoc(doc(admin,name,id))).data();
 async function seed(id,pickup){await setDoc(doc(kiosk,'orders',id),payload(pickup))}
 test('A-H. prepaid and pay-on-pickup follow atomic pending, cooking and ready boundaries',async()=>{for(const [index,type] of ['prepaid','pay_on_pickup'].entries()){const id=`r${index}`,pickup=Timestamp.fromMillis(2_000_000+index*10_000_000);await seed(id,pickup);let writes=[];const pending=await ops.startReservationLifecycleTransaction({db:compat(admin,writes),orderId:id,paymentType:type,expectedPickupAt:pickup,serverTimestamp,timestampFromMillis:Timestamp.fromMillis,adminId:'admin-one'});assert.deepEqual([pending.orderWrites,pending.displayWrites,pending.seatWrites,pending.paymentCalls],[1,0,0,0]);assert.deepEqual(writes,[`orders/${id}`]);let order=await read('orders',id);assert.equal(order.status,'reservation_pending');assert.equal(order.reservationPaymentType,type);writes=[];const cooking=await ops.advanceReservationLifecycleTransaction({db:compat(admin,writes),orderId:id,expectedLifecycleId:order.reservationLifecycleId,expectedPickupAt:pickup,nowMillis:pickup.toMillis()-900000,serverTimestamp,adminId:'admin-one',resolveBusinessDay:()=> '2026-08-19'});assert.equal(cooking.status,'cooking');assert.deepEqual(writes.sort(),[`orders/${id}`,`publicOrderDisplays/${id}`].sort());order=await read('orders',id);writes=[];const ready=await ops.advanceReservationLifecycleTransaction({db:compat(admin,writes),orderId:id,expectedLifecycleId:order.reservationLifecycleId,expectedPickupAt:pickup,nowMillis:pickup.toMillis(),serverTimestamp,adminId:'admin-one',resolveBusinessDay:()=> '2026-08-19'});assert.equal(ready.status,'ready');assert.equal((await read('orders',id)).reservationPaymentType,type);assert.equal((await read('publicOrderDisplays',id)).displayStatus,'ready');assert.equal((await read('publicOrderDisplays',id)).reservationOrder,true)}});
 test('I-M. non-admin, stale timestamp, invalid type, immediate and dine-in orders commit zero writes',async()=>{const pickup=Timestamp.fromMillis(9_000_000);await seed('guarded',pickup);for(const attempt of [()=>ops.startReservationLifecycleTransaction({db:compat(user),orderId:'guarded',paymentType:'prepaid',expectedPickupAt:pickup,serverTimestamp,timestampFromMillis:Timestamp.fromMillis,adminId:'user'}),()=>ops.startReservationLifecycleTransaction({db:compat(admin),orderId:'guarded',paymentType:'invalid',expectedPickupAt:pickup,serverTimestamp,timestampFromMillis:Timestamp.fromMillis,adminId:'admin-one'}),()=>ops.startReservationLifecycleTransaction({db:compat(admin),orderId:'guarded',paymentType:'prepaid',expectedPickupAt:Timestamp.fromMillis(1),serverTimestamp,timestampFromMillis:Timestamp.fromMillis,adminId:'admin-one'})])await assert.rejects(attempt);assert.equal((await read('orders','guarded')).status,'payment_pending')});
 test('N-P. concurrent administrators produce one lifecycle winner and no seat documents',async()=>{const pickup=Timestamp.fromMillis(20_000_000);await seed('race',pickup);const call=db=>ops.startReservationLifecycleTransaction({db:compat(db),orderId:'race',paymentType:'prepaid',expectedPickupAt:pickup,serverTimestamp,timestampFromMillis:Timestamp.fromMillis,adminId:'admin-one'}),other=env.authenticatedContext('admin-two',{admin:true}).firestore(),results=await Promise.allSettled([call(admin),call(other)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await read('orders','race')).status,'reservation_pending')});
}
