const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');

const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'admin.js'),'utf8');
const html=fs.readFileSync(path.join(root,'admin','index.html'),'utf8');
const digitSource=source.match(/const KOREAN_DIGIT_SPEECH[\s\S]*?\n}/)?.[0];
assert.ok(digitSource,'natural Korean number formatter exists');
const context={String,Number,Object};
vm.createContext(context);vm.runInContext(digitSource,context);
for(const [input,expected] of [[0,'영'],[7,'칠'],[10,'십'],[11,'십일'],[20,'이십'],[105,'백오'],[1000,'천'],[1010,'천십'],[3181,'삼천백팔십일'],[9999,'구천구백구십구'],['3,181','삼천백팔십일'],[' P3181 ','삼천백팔십일']])assert.strictEqual(context.spokenKoreanOrderNumber(input),expected);
for(const invalid of [null,undefined,'',NaN,Infinity,-1,10000,'12.3','abc'])assert.strictEqual(context.spokenKoreanOrderNumber(invalid),'');

assert.match(html,/id="adminVoiceSelect"/);assert.match(html,/id="adminVoicePreview"/);assert.match(html,/현재 음성/);
assert.match(source,/ADMIN_VOICE_STORAGE_KEY='pjAdminCustomerCallVoice'/);
assert.match(source,/sunhi\|선희.*heami\|혜미.*seoyeon\|서연.*natural\|online\|neural.*korean\|한국/i);
const voiceSource=source.slice(source.indexOf('const ADMIN_KOREAN_VOICE_PRIORITY'),source.indexOf('function renderAdminVoiceOptions'));
let saved=null;
const voiceContext={String,Object,Map,document:{getElementById:()=>null},window:{speechSynthesis:{getVoices:()=>[]}},localStorage:{getItem:()=>saved}};
vm.createContext(voiceContext);vm.runInContext(voiceSource,voiceContext);
const voiceList=[{name:'English Default',lang:'en-US',default:true},{name:'Generic Korean',lang:'ko-KR',localService:true},{name:'Microsoft SunHi Online (Natural)',lang:'ko-KR',localService:false},{name:'Microsoft SunHi Online (Natural)',lang:'ko-KR',localService:true}];
assert.strictEqual(voiceContext.uniqueAdminVoices(voiceList).length,3,'same name and language is deduplicated');
assert.match(voiceContext.selectAdminKoreanVoice(voiceList).name,/SunHi/,'SunHi wins Korean priority');
saved=JSON.stringify({name:'Generic Korean',lang:'ko-KR'});
assert.strictEqual(voiceContext.selectAdminKoreanVoice(voiceList).name,'Generic Korean','saved real voice is restored');
saved=JSON.stringify({name:'Missing Voice',lang:'ko-KR'});
assert.match(voiceContext.selectAdminKoreanVoice(voiceList).name,/SunHi/,'missing saved voice recovers to priority');
assert.strictEqual((source.match(/addEventListener\?\.\('voiceschanged'/g)||[]).length,1,'one late-loading listener');
assert.match(source,/adminVoiceRetryCount<3/);assert.match(source,/window\.speechSynthesis\.cancel\(\);\n  window\.speechSynthesis\.speak/);
assert.match(source,/Object\.freeze\(\{rate:\.94,pitch:1\.08,volume:1\}\)/);
assert.match(source,/voiceName:.*orderNumber:.*spokenText:/);
assert.match(source,/adminVoicePreview\.addEventListener\('click',\(\)=>enqueueCustomerCall\('3181','ko'\)\)/);
console.log('admin natural Korean number and selectable voice checks passed');
