const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const seatLayout=require('../seat-layout');
const operations=require('../admin-operations');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'seats.js'),'utf8'),html=fs.readFileSync(path.join(root,'seat/index.html'),'utf8');

function manager(initial={status:'empty'},confirmResult=true){
 const data={...initial},writes=[],listeners={},alerts=[];
 const snapshots=[];
 const elements={seatSummary:{innerHTML:''},seatAdmin:{innerHTML:'',addEventListener(type,fn){listeners[type]=fn},contains:()=>true},seatConnection:{},seatLayoutNotice:{},editSeatLayout:{addEventListener(){},focus(){}},saveSeatLayout:{addEventListener(){}},reloadSeatLayout:{addEventListener(){}},cancelSeatLayout:{addEventListener(){}},resetSeatLayout:{addEventListener(){}}};
 const db={collection(name){return {doc(id){return {id,onSnapshot(fn){if(name==='adminSettings')fn({exists:false})}}},onSnapshot(fn){if(name==='seats'){snapshots.push(fn);fn({forEach(cb){cb({id:'papa-2',data:()=>({...data})})}})}else fn({docs:[]})}}},async runTransaction(fn){let pending;const result=await fn({get:async()=>({exists:true,data:()=>({...data})}),set(_ref,payload){pending=payload}});if(pending){writes.push(pending);Object.assign(data,pending)}return result}};
 const context={console,db,PJAdminOperations:operations,document:{hidden:false,body:{classList:{add(){},toggle(){}}},getElementById:id=>elements[id]||null,querySelector:()=>null,addEventListener(){}},window:{top:null,PJSeatLayout:seatLayout,PJAdminOperations:operations,PJ_BOTTLE_SEAT_POLICY:{SUPPORTED_END_YEAR:2030,isBottleSeat:()=>false,getBottleSeatAvailability:()=>({available:true,reason:'open'}),millisecondsUntilNextBoundary:()=>86400000},addEventListener(){}},location:{assign(url){context.assigned=url},replace(){}},firebase:{auth:()=>({currentUser:{uid:'admin'},onAuthStateChanged(fn){fn({getIdTokenResult:async()=>({claims:{admin:true}})})},signOut:async()=>{}}),firestore:{FieldValue:{serverTimestamp:()=> 'SERVER'}}},confirm:()=>confirmResult,alert:message=>alerts.push(message),setTimeout:()=>0,clearTimeout(){},encodeURIComponent};context.window.top=context.window;vm.runInNewContext(source,context);return {context,data,writes,listeners,elements,snapshots,alerts};
}
function action(status,target,id='papa-2'){return {disabled:false,dataset:{seatId:id,seatFrom:status,seatTransition:target},closest(selector){return selector==='[data-seat-transition],[data-held-order]'?this:null}}}
function papaCard(output){return output.slice(output.indexOf('data-layout-seat-id="papa-2"'),output.indexOf('data-layout-seat-id="papa-bar4"'))}

test('seat manager loads the shared production policy and common stylesheet',()=>{
 assert.match(html,/admin\.css\?v=48\.0\.3/);assert.doesNotMatch(html,/admin\.css\?v=48\.0\.2/);assert.match(html,/admin-operations\.js\?v=48\.0\.2/);assert.match(html,/seats\.js\?v=48\.0\.1/);assert.match(html,/admin-operations[^]*seats\.js/);
 assert.match(source,/normalizeAdminSeatStatus,getAdminSeatActions,transitionAdminSeatState/);assert.doesNotMatch(source,/async function transitionReservation/);assert.doesNotMatch(source,/async function updateSeat/);
});
test('empty renders ordered use and reservation controls for every stable card',()=>{
 const m=manager();const card=m.elements.seatAdmin.innerHTML.match(/data-layout-seat-id="papa-2"[\s\S]*?<\/div><\/div><\/div>/)[0];
 assert.equal((m.elements.seatAdmin.innerHTML.match(/data-layout-seat-id=/g)||[]).length,13);assert.match(card,/>사용<\/button>[^]*>예약<\/button>/);assert.match(card,/data-seat-from="empty"/);assert.doesNotMatch(card,/>빈자리<\/button>/);
});
test('occupied renders only the empty action',()=>{const out=papaCard(manager({status:'occupied',occupiedAt:'OLD'}).elements.seatAdmin.innerHTML);assert.match(out,/data-seat-from="occupied"[^>]*>빈자리<\/button>/);assert.doesNotMatch(out,/>사용<\/button>/);assert.doesNotMatch(out,/>예약<\/button>/)});
test('reserved renders use then empty',()=>{const out=manager({status:'reserved'}).elements.seatAdmin.innerHTML;assert.match(out,/data-seat-from="reserved"[^>]*>사용<\/button>[^]*data-seat-from="reserved"[^>]*>빈자리<\/button>/);assert.doesNotMatch(out,/data-seat-from="reserved"[^>]*>예약<\/button>/)});
test('held without order is display-only and preserves every lease field',async()=>{const initial={status:'held',heldBy:'customer',heldAt:'A',heldUntil:'B',partySize:3};const m=manager(initial);assert.match(m.elements.seatAdmin.innerHTML,/주문중/);assert.doesNotMatch(m.elements.seatAdmin.innerHTML,/data-seat-from="held"/);for(const target of ['occupied','reserved','empty'])await assert.rejects(operations.transitionAdminSeatState({db:m.context.db,seatId:'papa-2',expectedStatus:'held',targetStatus:target,serverTimestamp:()=>1,supportedSeatIds:['papa-2']}),/허용되지/);assert.equal(m.writes.length,0);assert.deepEqual(m.data,initial)});
test('held with order keeps only order detail and no state buttons',async()=>{const initial={status:'held',orderId:'order-7',heldBy:'customer',heldAt:'A',heldUntil:'B',partySize:2};const m=manager(initial),out=papaCard(m.elements.seatAdmin.innerHTML);assert.match(out,/data-held-order="papa-2"[^>]*>주문 상세<\/button>/);assert.doesNotMatch(out,/data-seat-transition/);await assert.rejects(operations.transitionAdminSeatState({db:m.context.db,seatId:'papa-2',expectedStatus:'held',targetStatus:'empty',serverTimestamp:()=>1,supportedSeatIds:['papa-2']}));assert.equal(m.writes.length,0);assert.deepEqual(m.data,initial)});
test('unknown is not normalized to empty and has no controls',()=>{const m=manager({status:'mystery'}),out=papaCard(m.elements.seatAdmin.innerHTML);assert.match(out,/class="simple-seat seat-zone-papa unknown"/);assert.match(out,/확인 필요/);assert.doesNotMatch(out,/data-seat-transition/);assert.equal(m.writes.length,0)});
test('cancelled confirmation performs no transaction or local mutation',async()=>{const m=manager({status:'empty'},false),before={...m.data};await m.context.runSeatAction('papa-2','empty','reserved');assert.equal(m.writes.length,0);assert.deepEqual(m.data,before);assert.doesNotMatch(m.elements.seatAdmin.innerHTML,/aria-busy="true"/)});
test('successful action uses one transaction and waits for snapshot to unlock',async()=>{const m=manager({status:'empty'});await m.context.runSeatAction('papa-2','empty','reserved');assert.equal(m.writes.length,1);assert.equal(m.data.status,'reserved');assert.match(m.elements.seatAdmin.innerHTML,/aria-busy="true"/);m.snapshots[0]({forEach(cb){cb({id:'papa-2',data:()=>({...m.data})})}});assert.doesNotMatch(m.elements.seatAdmin.innerHTML,/aria-busy="true"/)});
test('delegated action stops propagation and invokes the shared transition once',async()=>{const m=manager({status:'empty'}),target=action('empty','occupied');let stopped=0;m.listeners.click({target,stopPropagation(){stopped++}});await new Promise(resolve=>setImmediate(resolve));assert.equal(stopped,1);assert.equal(m.writes.length,1);assert.equal(m.data.status,'occupied')});
test('layout edit mode renders no state controls and drag never calls a transaction',()=>{const m=manager();m.context.window.PJSeatLayoutEditor.startLayoutEdit();assert.doesNotMatch(m.elements.seatAdmin.innerHTML,/data-seat-transition/);m.listeners.dragstart({target:{closest:()=>({dataset:{layoutSeatId:'papa-2'},classList:{add(){}}})},dataTransfer:{setData(){}}});assert.equal(m.writes.length,0)});
test('held snapshot stays held without corrective write',()=>{const m=manager({status:'held',heldBy:'c',heldAt:'a',heldUntil:'u',partySize:4});m.snapshots[0]({forEach(cb){cb({id:'papa-2',data:()=>({...m.data})})}});const out=papaCard(m.elements.seatAdmin.innerHTML);assert.match(out,/주문중/);assert.doesNotMatch(out,/data-seat-transition/);assert.equal(m.writes.length,0);assert.equal(m.data.status,'held')});
test('all stable seat IDs and saved slot order survive the common action renderer',()=>{const out=manager().elements.seatAdmin.innerHTML,expected=['papa-2','papa-bar4','outdoor-1','outdoor-2','outdoor-3','outdoor-4','annex-1','annex-2','annex-3','annex-4','room-1','room-2','room-3'],rendered=[...out.matchAll(/data-layout-seat-id="([^"]+)"/g)].map(match=>match[1]);assert.equal(rendered.length,13);expected.forEach((id,index)=>assert.equal(rendered[index],id));assert.equal(new Set(rendered).size,13)});
test('common metadata is exhaustive and both UI sources contain no private policy table',()=>{const table={empty:['occupied','reserved'],occupied:['empty'],reserved:['occupied','empty'],held:[],unknown:[]};for(const [status,targets] of Object.entries(table)){assert.deepEqual(operations.getAdminSeatActions(status).map(action=>action.target),targets);assert.equal(operations.ADMIN_SEAT_STATUSES[status].label,{empty:'빈자리',occupied:'사용중',reserved:'예약',held:'주문중',unknown:'확인 필요'}[status])}assert.doesNotMatch(source,/const statusNames=\{/) });
test('all five confirmations are supplied only by common metadata',()=>{const expected={"empty:occupied":'이 좌석을 사용중으로 변경할까요?',"empty:reserved":'이 좌석을 예약으로 변경할까요?',"reserved:occupied":'예약 좌석의 이용을 시작하고 사용중으로 변경할까요?',"occupied:empty":'사용중인 좌석을 빈자리로 변경할까요?',"reserved:empty":'예약을 취소하고 빈자리로 변경할까요?'};for(const [key,message] of Object.entries(expected)){const [status,target]=key.split(':');assert.equal(operations.getAdminSeatActions(status).find(action=>action.target===target).confirmation,message);assert.doesNotMatch(source,new RegExp(message))}});
test('held rejection preserves every protected field for direct helper calls',async()=>{const initial={status:'held',heldBy:'owner',heldAt:'start',heldUntil:'expiry',partySize:5,orderId:'linked-order'},m=manager(initial);for(const target of ['occupied','reserved','empty'])await assert.rejects(operations.transitionAdminSeatState({db:m.context.db,seatId:'papa-2',expectedStatus:'held',targetStatus:target,serverTimestamp:()=>1,supportedSeatIds:['papa-2']}));for(const field of ['status','heldBy','heldAt','heldUntil','partySize','orderId'])assert.equal(m.data[field],initial[field]);assert.equal(m.writes.length,0)});
