const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {spawnElectronVerificationSync,assertElectronSucceeded}=require('./helpers/electron-verification-process');
const root=path.resolve(__dirname,'..');

test('drink volume, included sauce and independent quantities work in the real renderer',{timeout:120000},t=>{
 const report=path.join(os.tmpdir(),`drink-sauce-quantity-${process.pid}.json`),captures=fs.mkdtempSync(path.join(os.tmpdir(),'drink-sauce-captures-')),profile=fs.mkdtempSync(path.join(os.tmpdir(),'drink-sauce-profile-'));
 t.after(()=>fs.rmSync(report,{force:true}));t.after(()=>fs.rmSync(captures,{recursive:true,force:true}));t.after(()=>fs.rmSync(profile,{recursive:true,force:true}));
 const run=spawnElectronVerificationSync(['scripts/verify-drink-sauce-order-quantity.js'],{cwd:root,encoding:'utf8',env:{...process.env,DRINK_SAUCE_QUANTITY_REPORT:report,DRINK_SAUCE_QUANTITY_CAPTURE_DIR:captures,ELECTRON_VERIFICATION_USER_DATA:profile},timeout:110000,maxBuffer:10*1024*1024});
 assertElectronSucceeded(assert,run,report);const result=JSON.parse(fs.readFileSync(report,'utf8'));
 if(result.drinkRows.clipped)console.error('DRINK_VOLUME_GEOMETRY_DIAGNOSTICS',JSON.stringify(result.drinkRows.diagnostics,null,2));
 assert.equal(result.initial.extras!==null,true);assert.match(result.initial.labels,/1\.25L/);assert.equal(result.initial.clipped.length,0);assert.equal(result.initial.documentOverflow[0],0);
 assert.deepEqual(result.initial.extraRows.map(row=>[row.name,row.quantity,row.amount]),[['치즈 스틱 × 1',1,'9,900원'],['코카-콜라 1.25L × 1',1,'2,500원']]);
 assert.match(result.initial.extraTotal,/추가 상품 합계/);assert.match(result.initial.extraTotal,/12,400원/);assert.equal(result.initial.extraRows.every(row=>row.amount!=='0원'&&row.nameColor!=='rgb(255, 255, 255)'&&row.amountColor!=='rgb(255, 255, 255)'),true);
 assert.equal(result.drinkRows.rows.length,8);assert.equal(result.drinkRows.clipped,0,JSON.stringify(result.drinkRows.clippedDetails));assert.deepEqual(result.drinkRows.documentOverflow,[0,0]);for(const row of result.drinkRows.rows){assert.match(row.volume,/^(?:500mL|1\.(?:25|5)L)$/);assert.match(row.price,/^(?:1,800|2,500)원$/);assert.equal(row.volumeColor,'rgb(255, 255, 255)');assert.equal(row.quantityColor,'rgb(17, 17, 17)');assert.ok(row.volumeRect.right<=row.minusRect.left);assert.ok(row.minusRect.width>=44&&row.minusRect.height>=44);assert.ok(row.plusRect.width>=44&&row.plusRect.height>=44)}
 assert.deepEqual(result.visualStates.base1.meta.length,4);assert.equal(result.visualStates.base2.quantity,2);assert.equal(result.visualStates.base9.quantity,9);assert.equal(result.visualStates.base9.clipped,0);assert.equal(result.visualStates.extra2,2);assert.equal(result.visualStates.extra9,9);
 assert.equal(result.mutation.doubled-result.mutation.start,33000);assert.equal(result.mutation.restored,result.mutation.start);assert.deepEqual(result.mutation.extrasAfter,result.mutation.extras);assert.equal(result.mutation.limitModal,'quantityLimit');assert.equal(result.mutation.deleteModal,'quantityDelete');assert.equal(result.mutation.cancelPreserves,true);assert.equal(result.mutation.finalCount,2);
 assert.deepEqual(result.extraMutation,{before:1,after:2,restored:1,baseQty:1,total:84800});
 assert.equal(result.locales.length,6);for(const row of result.locales){assert.equal(row.clipped.length,0,row.locale);assert.equal(row.documentOverflow[0],0,row.locale);assert.equal(row.controls.every(rect=>rect.height>=44),true,row.locale)}
 assert.deepEqual(result.focusRestore,{opened:true,restored:true});
 assert.deepEqual(result.setDrinkNextFlow,{upsell:'setDrinkUpsell',included:'includedSauce',labels:['추가안함','추가선택'],fontSizes:['28px','28px'],afterNext:{step:'review',modal:null,orders:1}});
 assert.equal(result.finalSideFlow.paths.every(row=>row.modal==='includedSauce'),true);assert.equal(result.finalSideFlow.modal,'includedSauce');assert.equal(result.finalSideFlow.count,1);assert.deepEqual(result.finalSideFlow.labels,['추가안함','추가선택']);assert.equal(result.finalSideFlow.extrasStep,'accompaniment');assert.equal(result.finalSideFlow.existingCartModal,'includedSauce');assert.deepEqual(result.finalSideFlow.noExtra,{step:'review',modal:null,orders:2});
 assert.equal(result.sauceTakeout.modal,'includedSauce');assert.deepEqual(result.sauceTakeout.summary,{garlic:2,pickle:1,hotSauce:2,honeyMustard:0,tomato:1,storeFree:[]});assert.match(result.sauceTakeout.text,/토마토소스/);
 assert.deepEqual(result.sauceDinein.summary.storeFree,['pickle','hotSauce']);assert.match(result.sauceDinein.text,/무료/);
 assert.deepEqual(result.firestoreIsolation,{externalRequests:0,requests:[],operatingReads:0,operatingWrites:0,authAttempts:0,listenerMode:'test-stub'});
 assert.ok(result.phoneModal.rect.top>=0);assert.ok(result.phoneModal.rect.bottom<=844);assert.equal(result.phoneModal.documentOverflow,0);assert.ok(result.phoneModal.scrollHeight>=result.phoneModal.clientHeight);
 assert.equal(result.phoneReview.layout,'phone');assert.deepEqual(result.phoneReview.documentOverflow,[0,0]);assert.deepEqual(result.phoneReview.overlaps,{frameSummary:0,listSummary:0,controlsSummary:0,summaryActions:0,actionsNetwork:0,summaryNetwork:0});assert.deepEqual(result.phoneReview.clipped,[]);assert.ok(result.phoneReview.listScroll[1]>result.phoneReview.listScroll[0]);assert.ok(result.phoneReview.summary.top>=result.phoneReview.frame.bottom);assert.ok(result.phoneReview.actions.top>=result.phoneReview.summary.bottom);assert.ok(result.phoneReview.network.bottom<=844);for(const button of result.phoneReview.buttons){assert.ok(button.top>=result.phoneReview.actions.top);assert.ok(button.bottom<=result.phoneReview.actions.bottom)}
 assert.equal(result.viewportMatrix.length,13*6);for(const row of result.viewportMatrix){const name=`${row.width}x${row.height}/${row.locale}`;assert.equal(row.review.documentOverflow[0],0,name);assert.deepEqual(row.review.clipped,[],name);assert.equal(row.review.lastReachable,true,name);assert.equal(row.review.paidZero,0,name);assert.ok(row.review.extraTotal,name);assert.equal(row.drink.documentOverflow[0],0,name);assert.deepEqual(row.drink.clipped,[],name);assert.equal(row.drink.buttons,true,name);assert.equal(row.modal.documentOverflow[0],0,name);assert.equal(row.modal.clipped,0,name);assert.equal(row.modal.highlight,true,name);assert.equal(row.modal.buttons,true,name);assert.ok(row.modal.rect[0]>=0&&row.modal.rect[1]>=0&&row.modal.rect[2]<=row.width&&row.modal.rect[3]<=row.height,name)}
 for(const name of result.captures)assert.equal(fs.existsSync(path.join(captures,name)),true,name);
});
