const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {assertElectronSucceeded,spawnElectronVerificationSync}=require('./helpers/electron-verification-process');
const root=path.resolve(__dirname,'..');
const locale=require('../waiting-tv/waiting-tv-locales.js');
const expectedDensity=count=>count<=1?'single':count===2?'double':count===3?'triple':count===4?'compact':'dense';
// The former 22px check measured the first status span by accident; guidance has always used the 18–19px adaptive helper scale on main.
const portraitGuidanceBaseline=[19.44,19.008,18.576,18.144,18];
const portraitIdentityBaseline=[75.6,68.58,62.1,56.16,50.22];
const metricFailure=(context,column,list,metric)=>`${context} density=${list.density} orderCount=${metric.orderCount??list.count} column=${column} card=${metric.orderKey||metric.cardIndex} identityType=${metric.identityType} identityLength=${metric.identityLength??'-'} lengthClass=${metric.lengthClass||'none'} selector=${metric.selector} text=${JSON.stringify(metric.text||'')} font=${JSON.stringify({family:metric.fontFamily,size:metric.fontSize,weight:metric.fontWeight,lineHeight:metric.lineHeight})} client=${metric.clientWidth}x${metric.clientHeight} scroll=${metric.scrollWidth}x${metric.scrollHeight} contentRect=${JSON.stringify(metric.contentRect)} textSafety=${JSON.stringify(metric.textSafety)} clipping=${metric.clipping} cardRect=${JSON.stringify(metric.cardRect)} cardSafety=${JSON.stringify(metric.cardSafety)} densityClass=${metric.densityClass} sameNode=${metric.sameNode}`;
const assertMetric=(assert,context,column,list,metric,minimumFontSize,{identity=false}={})=>{const details=metricFailure(context,column,list,metric);assert.equal(metric.missing,undefined,details);assert.ok(metric.scrollWidth<=metric.clientWidth,details);assert.ok(metric.scrollHeight<=metric.clientHeight,details);assert.ok(metric.fontSize>=minimumFontSize,details);assert.ok(metric.textSafety&&Object.values(metric.textSafety).every(value=>value>=0),details);assert.ok(metric.cardSafety&&Object.values(metric.cardSafety).every(value=>value>=0),details);assert.equal(metric.writingMode,'horizontal-tb',details);if(identity){assert.ok(metric.lineBoxSafety>=4,details);assert.ok(metric.textSafety.top>=1,details);assert.ok(metric.textSafety.bottom>=1,details);assert.ok(metric.textSafety.top+metric.textSafety.bottom>=6,details)}};
const assertLayout=(sample,context)=>{
 assert.equal(sample.cooking.density,expectedDensity(sample.cooking.count),`${context} cooking density`);assert.equal(sample.ready.density,expectedDensity(sample.ready.count),`${context} ready density`);
 assert.equal(sample.cooking.clipping,false,`${context} cooking clipping: ${JSON.stringify(sample.cooking.elements)}`);assert.equal(sample.ready.clipping,false,`${context} ready clipping: ${JSON.stringify(sample.ready.elements)}`);assert.equal(sample.cooking.overlap,false);assert.equal(sample.ready.overlap,false);assert.equal(sample.cooking.internalOverlap,false);assert.equal(sample.ready.internalOverlap,false);assert.equal(sample.cooking.verticalKorean,false);assert.equal(sample.ready.verticalKorean,false);assert.ok(sample.cooking.maxTextLines<=2);assert.ok(sample.ready.maxTextLines<=2);
 assert.equal(sample.horizontalOverflow,0);assert.equal(sample.documentVerticalOverflow,0);assert.equal(sample.headerOverlap,false);assert.equal(sample.buttonOverlap,false);assert.equal(sample.logoOverlap,false);
 for(const [column,list] of Object.entries({cooking:sample.cooking,ready:sample.ready}))if(list.card){assert.equal(list.card.scrollWidth,list.card.clientWidth);assert.equal(list.card.scrollHeight,list.card.clientHeight);assert.ok(parseFloat(list.numberFontSize)>=32);assert.ok(parseFloat(list.guidanceFontSize)>=18);if(list.helperFontSize)assert.ok(parseFloat(list.helperFontSize)>=18);assert.equal(list.selectorIntegrity.identityCount,list.count,`${context} ${column} identity selector count`);assert.equal(list.selectorIntegrity.guidanceCount,list.count,`${context} ${column} guidance selector count`);assert.equal(list.selectorIntegrity.statusCount,list.count,`${context} ${column} status selector count`);assert.equal(list.selectorIntegrity.exact,true,`${context} ${column} exact semantic selectors`);assert.equal(list.selectorIntegrity.distinct,true,`${context} ${column} guidance and status must be different nodes`);for(const identity of list.identityMetrics)assertMetric(assert,context,column,list,identity,32,{identity:true});for(const guidance of list.guidanceMetrics){assert.equal(guidance.sameNode,false,metricFailure(context,column,list,guidance));assertMetric(assert,context,column,list,guidance,18)}for(const status of list.statusMetrics){assert.equal(status.sameNode,false,metricFailure(context,column,list,status));assertMetric(assert,context,column,list,status,18);assert.ok(status.lineBoxSafety>=8,metricFailure(context,column,list,status))}for(const timing of list.timingMetrics)assertMetric(assert,context,column,list,timing,18)}
};

test('actual waiting-TV Chromium applies independent adaptive density without clipping or document overflow',{timeout:180000},t=>{
 const tempRoot=fs.mkdtempSync(path.join(os.tmpdir(),'waiting-tv-density-test-')),report=path.join(tempRoot,'report.json'),screens=path.join(tempRoot,'screens'),profile=path.join(tempRoot,'profile');
 t.after(()=>fs.rmSync(tempRoot,{recursive:true,force:true}));
 const run=spawnElectronVerificationSync(['scripts/verify-waiting-tv-density.js'],{cwd:root,encoding:'utf8',env:{...process.env,WAITING_TV_DENSITY_REPORT:report,WAITING_TV_DENSITY_SCREENSHOTS:screens,WAITING_TV_DENSITY_USER_DATA:profile,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'},timeout:170000,maxBuffer:10*1024*1024});
 assertElectronSucceeded(assert,run,report);const result=JSON.parse(fs.readFileSync(report,'utf8'));
 for(const [viewport,languages] of Object.entries(result.locales))for(const [language,samples] of Object.entries(languages))for(const [name,sample] of Object.entries(samples)){assertLayout(sample,`${viewport} ${language} ${name}`);for(const list of [sample.cooking,sample.ready])assert.ok(list.languages.every(value=>value===language),`${viewport} ${language} ${name} card language independence`)}
 const portrait=result.viewports['1080x1920'];const readySteps=[1,2,3,4,5].map(count=>portrait[`ready-${count}`].ready);
 const allMetrics=Object.values(result.locales).flatMap(languages=>Object.values(languages)).flatMap(samples=>Object.values(samples)).flatMap(sample=>[sample.cooking,sample.ready]).flatMap(list=>[...list.identityMetrics,...list.statusMetrics,...list.guidanceMetrics,...list.timingMetrics]);
 console.log(`waiting-TV typography matrix: viewports=${Object.keys(result.locales).length} locales=${Object.keys(result.locales['1080x1920']).length} scenarios=${Object.keys(result.locales['1080x1920'].ko).length} metrics=${allMetrics.length} minFont=${Math.min(...allMetrics.map(metric=>metric.fontSize))} maxOverflow=${Math.max(...allMetrics.map(metric=>Math.max(metric.overflowX,metric.overflowY)))} minTextSafety=${Math.min(...allMetrics.flatMap(metric=>Object.values(metric.textSafety)))}`);
 for(const [index,list] of readySteps.entries()){assert.ok(parseFloat(list.guidanceFontSize)>=portraitGuidanceBaseline[index],`1080x1920 guidance density ${list.density} regressed below main baseline ${portraitGuidanceBaseline[index]}px`)}
 for(const [index,list] of readySteps.entries()){assert.ok(parseFloat(list.numberFontSize)>=portraitIdentityBaseline[index]-2,`1080x1920 identity density ${list.density} shrank by more than 2px`)}
 for(const [viewport,languages] of Object.entries(result.locales))for(const [language,samples] of Object.entries(languages)){const steps=[1,2,3,4,5].map(count=>samples[`ready-${count}`].ready);for(let index=1;index<steps.length;index++){assert.ok(parseFloat(steps[index].numberFontSize)<parseFloat(steps[index-1].numberFontSize),`${viewport} ${language} identity density order`);assert.ok(parseFloat(steps[index].guidanceFontSize)<=parseFloat(steps[index-1].guidanceFontSize),`${viewport} ${language} guidance density order`);assert.ok(parseFloat(steps[index].statusFontSize)<parseFloat(steps[index-1].statusFontSize),`${viewport} ${language} status density order`)}}
 for(let index=1;index<readySteps.length;index++){assert.ok(parseFloat(readySteps[index].helperFontSize)<=parseFloat(readySteps[index-1].helperFontSize));assert.ok(readySteps[index].card.clientHeight<readySteps[index-1].card.clientHeight)}
 assert.deepEqual([portrait['mixed-4-1'].cooking.density,portrait['mixed-4-1'].ready.density],['compact','single']);assert.deepEqual([portrait['mixed-1-4'].cooking.density,portrait['mixed-1-4'].ready.density],['single','compact']);
 assert.deepEqual([result.transitions.cookingToReady.cooking.count,result.transitions.cookingToReady.ready.count],[3,1]);assert.deepEqual([result.transitions.pickupDeleted.cooking.count,result.transitions.pickupDeleted.ready.count],[3,0]);assert.equal(result.transitions.pickupDeleted.cooking.density,'triple');assert.ok(parseFloat(result.transitions.cookingToReady.cooking.numberFontSize)>parseFloat(result.transitions.cooking5.cooking.numberFontSize),'density decrease immediately restores larger type');assert.equal(result.transitions.pickupDeleted.ready.card,null,'pickup completion removes the ready DOM card');assert.deepEqual(result.consoleProblems,[]);assert.equal(fs.readdirSync(screens).length,8);
 assert.deepEqual(result.semantics.mixed.cooking.languages,['ko','ja','vi']);assert.deepEqual(result.semantics.mixed.ready.languages,['en','zh','es']);
 const mixedText=[...result.semantics.mixed.cooking.texts,...result.semantics.mixed.ready.texts].join('\n');
 for(const language of locale.supportedLanguages){assert.ok(mixedText.includes(locale.format(language,language==='vi'?'reservationCooking':language==='es'?'reservationReady':language==='ko'||language==='ja'?'cooking':'ready')),`${language} mixed status`);assert.ok(mixedText.includes(locale.format(language,language==='ko'||language==='ja'||language==='vi'?'cookingGuidance':'readyGuidance')),`${language} mixed guidance`)}
 assert.ok(result.semantics.mixed.cooking.texts[0].includes(locale.format('ko','countdown',{time:'08:20'}).slice(0,-5)),'countdown remains localized while decreasing');
 assert.ok(result.semantics.mixed.cooking.texts[2].includes(locale.format('vi','scheduledPickup',{time:''}).trim()));assert.ok(result.semantics.mixed.ready.texts[2].includes(locale.format('es','scheduledPickup',{time:''}).trim()));
 assert.deepEqual(result.semantics.fallback.cooking.languages,['ko','ko']);assert.deepEqual(result.semantics.fallback.ready.languages,['ko','ko']);assert.ok([...result.semantics.fallback.cooking.texts,...result.semantics.fallback.ready.texts].every(text=>/[가-힣]/.test(text)),'damaged languages render Korean without dropping cards');
 for(const viewport of Object.values(result.locales))for(const [language,samples] of Object.entries(viewport))if(language!=='ko'){assertLayout(samples['reservation-1-1'],`${language} reservation long-name typography`);assert.ok(samples['reservation-1-1'].ready.identityMetrics[0].text.length>=8,`${language} synthetic long-name fixture`)}
 const expectedLengthClass=length=>length<=10?'':length<=15?'name-length-long':'name-length-maximum';
 for(const [viewport,languages] of Object.entries(result.locales))for(const [language,samples] of Object.entries(languages))if(language!=='ko'){const base=samples['name-length-10'].cooking.identityMetrics[0].fontSize;for(const length of [1,10,11,15,16,20]){const metric=samples[`name-length-${length}`].cooking.identityMetrics[0],details=metricFailure(`${viewport} ${language} name-length-${length}`,'cooking',samples[`name-length-${length}`].cooking,metric);assert.equal(metric.identityLength,length,details);assert.equal(metric.lengthClass,expectedLengthClass(length),details);assert.equal(metric.clipping,false,details);assert.notEqual(metric.text,'',details);assert.ok(samples[`name-length-${length}`].cooking.maxTextLines<=2,details)}assert.ok(Math.abs(samples['name-length-11'].cooking.identityMetrics[0].fontSize/base-.9)<.001,`${viewport} ${language} 11-char scale`);assert.ok(Math.abs(samples['name-length-16'].cooking.identityMetrics[0].fontSize/base-.82)<.001,`${viewport} ${language} 16-char scale`)}
 assert.deepEqual(result.transitions.longNameRepeat,result.transitions.longNameFirst,'same long-name snapshot rerender preserves text, class and typography');
});
