const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {assertElectronSucceeded,spawnElectronVerificationSync}=require('./helpers/electron-verification-process');
const root=path.resolve(__dirname,'..');
const locale=require('../waiting-tv/waiting-tv-locales.js');
const expectedDensity=count=>count<=1?'single':count===2?'double':count===3?'triple':count===4?'compact':'dense';
// The former 22px check measured the first status span by accident; guidance has always used the 18–19px adaptive helper scale on main.
const portraitGuidanceBaseline=[19.44,19.008,18.576,18.144,18];
const metricFailure=(context,column,list,metric)=>`${context} density=${list.density} column=${column} card=${metric.orderKey||metric.cardIndex} selector=${metric.selector} text=${JSON.stringify(metric.text||'')} fontSize=${metric.fontSize} client=${metric.clientWidth}x${metric.clientHeight} scroll=${metric.scrollWidth}x${metric.scrollHeight} lineHeight=${metric.lineHeight} cardRect=${JSON.stringify(metric.cardRect)} sameNode=${metric.sameNode}`;
const assertLayout=(sample,context)=>{
 assert.equal(sample.cooking.density,expectedDensity(sample.cooking.count),`${context} cooking density`);assert.equal(sample.ready.density,expectedDensity(sample.ready.count),`${context} ready density`);
 assert.equal(sample.cooking.clipping,false,`${context} cooking clipping: ${JSON.stringify(sample.cooking.elements)}`);assert.equal(sample.ready.clipping,false,`${context} ready clipping: ${JSON.stringify(sample.ready.elements)}`);assert.equal(sample.cooking.overlap,false);assert.equal(sample.ready.overlap,false);assert.equal(sample.cooking.internalOverlap,false);assert.equal(sample.ready.internalOverlap,false);assert.equal(sample.cooking.verticalKorean,false);assert.equal(sample.ready.verticalKorean,false);assert.ok(sample.cooking.maxTextLines<=2);assert.ok(sample.ready.maxTextLines<=2);
 assert.equal(sample.horizontalOverflow,0);assert.equal(sample.documentVerticalOverflow,0);assert.equal(sample.headerOverlap,false);assert.equal(sample.buttonOverlap,false);assert.equal(sample.logoOverlap,false);
 for(const [column,list] of Object.entries({cooking:sample.cooking,ready:sample.ready}))if(list.card){assert.equal(list.card.scrollWidth,list.card.clientWidth);assert.equal(list.card.scrollHeight,list.card.clientHeight);assert.ok(parseFloat(list.numberFontSize)>=34);assert.ok(parseFloat(list.guidanceFontSize)>=18);if(list.helperFontSize)assert.ok(parseFloat(list.helperFontSize)>=18);assert.equal(list.selectorIntegrity.guidanceCount,list.count,`${context} ${column} guidance selector count`);assert.equal(list.selectorIntegrity.statusCount,list.count,`${context} ${column} status selector count`);assert.equal(list.selectorIntegrity.exact,true,`${context} ${column} exact semantic selectors`);assert.equal(list.selectorIntegrity.distinct,true,`${context} ${column} guidance and status must be different nodes`);for(const guidance of list.guidanceMetrics){const details=metricFailure(context,column,list,guidance);assert.equal(guidance.missing,undefined,details);assert.equal(guidance.sameNode,false,details);assert.ok(guidance.scrollWidth<=guidance.clientWidth,details);assert.ok(guidance.scrollHeight<=guidance.clientHeight,details);assert.ok(guidance.fontSize>=18,details)}for(const status of list.statusMetrics){const details=metricFailure(context,column,list,status);assert.equal(status.missing,undefined,details);assert.equal(status.sameNode,false,details);assert.ok(status.scrollWidth<=status.clientWidth,details);assert.ok(status.scrollHeight<=status.clientHeight,details);assert.ok(status.fontSize>=18,details);assert.ok(status.lineBoxSafety>=8,details)}}
};

test('actual waiting-TV Chromium applies independent adaptive density without clipping or document overflow',{timeout:180000},t=>{
 const tempRoot=fs.mkdtempSync(path.join(os.tmpdir(),'waiting-tv-density-test-')),report=path.join(tempRoot,'report.json'),screens=path.join(tempRoot,'screens'),profile=path.join(tempRoot,'profile');
 t.after(()=>fs.rmSync(tempRoot,{recursive:true,force:true}));
 const run=spawnElectronVerificationSync(['scripts/verify-waiting-tv-density.js'],{cwd:root,encoding:'utf8',env:{...process.env,WAITING_TV_DENSITY_REPORT:report,WAITING_TV_DENSITY_SCREENSHOTS:screens,WAITING_TV_DENSITY_USER_DATA:profile,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'},timeout:170000,maxBuffer:10*1024*1024});
 assertElectronSucceeded(assert,run,report);const result=JSON.parse(fs.readFileSync(report,'utf8'));
 for(const [viewport,languages] of Object.entries(result.locales))for(const [language,samples] of Object.entries(languages))for(const [name,sample] of Object.entries(samples)){assertLayout(sample,`${viewport} ${language} ${name}`);for(const list of [sample.cooking,sample.ready])assert.ok(list.languages.every(value=>value===language),`${viewport} ${language} ${name} card language independence`)}
 const portrait=result.viewports['1080x1920'];const readySteps=[1,2,3,4,5].map(count=>portrait[`ready-${count}`].ready);
 const windowsParity=portrait['cooking-1'].cooking.statusMetrics[0];console.log(`waiting-TV 1080x1920 ko cooking-1 status: ${JSON.stringify(windowsParity)}`);
 for(const [index,list] of readySteps.entries()){assert.ok(parseFloat(list.guidanceFontSize)>=portraitGuidanceBaseline[index],`1080x1920 guidance density ${list.density} regressed below main baseline ${portraitGuidanceBaseline[index]}px`)}
 for(let index=1;index<readySteps.length;index++){assert.ok(parseFloat(readySteps[index].numberFontSize)<parseFloat(readySteps[index-1].numberFontSize));assert.ok(parseFloat(readySteps[index].guidanceFontSize)<=parseFloat(readySteps[index-1].guidanceFontSize));assert.ok(parseFloat(readySteps[index].statusFontSize)<parseFloat(readySteps[index-1].statusFontSize));assert.ok(parseFloat(readySteps[index].helperFontSize)<=parseFloat(readySteps[index-1].helperFontSize));assert.ok(readySteps[index].card.clientHeight<readySteps[index-1].card.clientHeight)}
 assert.deepEqual([portrait['mixed-4-1'].cooking.density,portrait['mixed-4-1'].ready.density],['compact','single']);assert.deepEqual([portrait['mixed-1-4'].cooking.density,portrait['mixed-1-4'].ready.density],['single','compact']);
 assert.deepEqual([result.transitions.cookingToReady.cooking.count,result.transitions.cookingToReady.ready.count],[3,1]);assert.deepEqual([result.transitions.pickupDeleted.cooking.count,result.transitions.pickupDeleted.ready.count],[3,0]);assert.equal(result.transitions.pickupDeleted.cooking.density,'triple');assert.ok(parseFloat(result.transitions.cookingToReady.cooking.numberFontSize)>parseFloat(result.transitions.cooking5.cooking.numberFontSize),'density decrease immediately restores larger type');assert.equal(result.transitions.pickupDeleted.ready.card,null,'pickup completion removes the ready DOM card');assert.deepEqual(result.consoleProblems,[]);assert.equal(fs.readdirSync(screens).length,8);
 assert.deepEqual(result.semantics.mixed.cooking.languages,['ko','ja','vi']);assert.deepEqual(result.semantics.mixed.ready.languages,['en','zh','es']);
 const mixedText=[...result.semantics.mixed.cooking.texts,...result.semantics.mixed.ready.texts].join('\n');
 for(const language of locale.supportedLanguages){assert.ok(mixedText.includes(locale.format(language,language==='vi'?'reservationCooking':language==='es'?'reservationReady':language==='ko'||language==='ja'?'cooking':'ready')),`${language} mixed status`);assert.ok(mixedText.includes(locale.format(language,language==='ko'||language==='ja'||language==='vi'?'cookingGuidance':'readyGuidance')),`${language} mixed guidance`)}
 assert.ok(result.semantics.mixed.cooking.texts[0].includes(locale.format('ko','countdown',{time:'08:20'}).slice(0,-5)),'countdown remains localized while decreasing');
 assert.ok(result.semantics.mixed.cooking.texts[2].includes(locale.format('vi','scheduledPickup',{time:''}).trim()));assert.ok(result.semantics.mixed.ready.texts[2].includes(locale.format('es','scheduledPickup',{time:''}).trim()));
 assert.deepEqual(result.semantics.fallback.cooking.languages,['ko','ko']);assert.deepEqual(result.semantics.fallback.ready.languages,['ko','ko']);assert.ok([...result.semantics.fallback.cooking.texts,...result.semantics.fallback.ready.texts].every(text=>/[가-힣]/.test(text)),'damaged languages render Korean without dropping cards');
});
