const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {assertElectronSucceeded,spawnElectronSync}=require('./helpers/electron-verification-process');
const root=path.resolve(__dirname,'..');
test('actual Chromium unlocks and reuses one completion AudioContext without duplicate alerts',{timeout:120000},t=>{
 const tempRoot=fs.mkdtempSync(path.join(os.tmpdir(),'waiting-tv-completion-test-')),report=path.join(tempRoot,'report.json'),screenshot=path.join(tempRoot,'completion.png'),mixedScreenshot=path.join(tempRoot,'mixed.png'),userData=path.join(tempRoot,'profile');t.after(()=>fs.rmSync(tempRoot,{recursive:true,force:true}));
 const run=spawnElectronSync(require('electron'),['scripts/verify-waiting-tv-completion.js'],{cwd:root,encoding:'utf8',env:{...process.env,WAITING_TV_REPORT:report,WAITING_TV_SCREENSHOT:screenshot,WAITING_TV_MIXED_SCREENSHOT:mixedScreenshot,WAITING_TV_USER_DATA:userData,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'},timeout:110000,maxBuffer:10*1024*1024});
 assertElectronSucceeded(assert,run,report);
 const result=JSON.parse(fs.readFileSync(report,'utf8'));
 assert.deepEqual(result.initial,{starts:0,contexts:0,ready:0,button:'알림음·음성 안내 시작'});assert.equal(result.unlock.contexts,1);assert.equal(result.unlock.resumeCalls,1);assert.equal(result.unlock.state,'running');assert.equal(result.unlock.button,'알림음·음성 안내 켜짐');
 assert.equal(result.transition.starts,2);assert.match(result.transition.ready,/1111번.*포장 주문이 완료되었습니다.*카운터에서 주문을 받아주세요/s);assert.equal(result.duplicate,2);
 assert.deepEqual(result.reload,{starts:0,ready:1});assert.equal(result.newReady,2);assert.equal(result.twoOrders,6);
 assert.equal(result.resumeFailure.starts,result.resumeFailure.before);assert.equal(result.resumeFailure.resumeCalls,2);assert.match(result.resumeFailure.ready,/5555번/);assert.match(result.resumeFailure.button,/알림음 차단됨/);
 assert.equal(result.hidden,result.resumeFailure.starts);assert.equal(result.removed,0);assert.equal(result.reappeared,result.resumeFailure.starts);assert.deepEqual({...result.maximum,gridScroll:undefined},{count:24,longNumber:true,gridScroll:undefined,horizontalOverflow:0,verticalOverflow:0,headerOverlap:false});assert.ok(result.maximum.gridScroll>0);
 assert.deepEqual(result.mixed,{cooking:2,ready:2,headerOverlap:false});
 assert.deepEqual({...result.layout,logo:undefined},{viewport:[1080,1920],horizontalOverflow:0,verticalOverflow:0,clipped:0,overlap:false,logo:undefined});assert.equal(result.layout.logo.width,225);assert.equal(result.layout.logo.height,96);assert.ok(Math.abs(result.layout.logo.left-43.2)<0.1);assert.equal(result.layout.logo.top,21);assert.equal(result.layout.logo.background,'rgba(0, 0, 0, 0)');assert.equal(result.layout.logo.padding,'0px');assert.equal(result.layout.logo.filter,'brightness(0) invert(1)');assert.equal(result.layout.logo.clipped,false);assert.equal(result.layout.logo.overlap,false);assert.deepEqual(result.consoleProblems,[]);assert.ok(fs.statSync(screenshot).size>10000);assert.ok(fs.statSync(mixedScreenshot).size>10000);
});
