window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.en={
    meta:{htmlLang:'en',title:'Papa John\'s Mobile Kiosk V13'},
    labels:{orderType:{takeout:'Takeout',dinein:'Dine in'},promo:{normal:'Regular Order',takeout:'Takeout 20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'Set Menu'},dough:{original:'Original',thin:'Thin Crust',croissant:'Croissant'},crust:{original:'Original',cheeseRoll:'Cheese Roll',goldRing:'Gold Ring',thin:'Thin Crust',croissant:'Croissant'},size:{R:'Regular Size',L:'Large Size',F:'Family Size'},payment:{cash:'Cash',card:'Credit Card',meal_ticket:'Meal Ticket',bizle:'Bizle Meal Ticket'}},
    home:{location:'Papa John\'s Pangyo 2 Techno Valley',headlinePrefix:'Enjoy ',headlineAccent:'freshly baked',headlineSuffix:' pizza today!',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'Dine in',dineInFeatureMeal:'Comfortable in-store dining',dineInFeatureSeats:'Various seating options',dineInFeatureSet:'Order set menus',takeoutTitle:'Takeout',takeoutFeatureFast:'Fast and easy takeout',takeoutFeatureReady:'Ready for quick pickup',takeoutFeatureBenefit:'Discount benefits',happyHourDeal:'R size pizza 15,000 won',takeoutDeal:'L/F takeout 20% off',takeoutDealDesc:'Order now with takeout discount',beerTitle:'Pizza & beer available!',beerHeineken:'Heineken draft beer 8,000 won',beerBudweiser:'Budweiser bottled beer 5,000 won'},
    orderType:{title:'How would you like to order?'},
    benefit:{title:'Choose your order benefit',subtitle:{dinein:'Choose from Set Menu, UP & UP, or Regular Order.',takeout:'Choose the benefit you want.'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP is only for pizzas sold in Large size. Pay the Large pizza price and upgrade to Family size with your selected crust for free.'},card:{set:{title:'Set Menu',desc:'For 2 · 3 · 4 guests',pill:'Balanced set by party size'},upup:{title:'UP & UP',desc:'Upgrade Large pizza to Family',pill:'Free crust upgrade'},normal:{title:'Regular Order',desc:'Choose your menu and options',pill:'Order freely',sideDrinkOnlyDesc:'You can also order only sides and drinks.'},happy:{title:'HAPPY HOUR',desc:'16:00–20:00 R size',pill:'15,000 won'},takeout:{title:'Takeout 20%',desc:'L/F pizza takeout',pill:'20% off'}},setChoice:{title:'Choose a set menu',subtitle:'Check the set for your party size, then choose one.',select:'Select →',note:'Set menus are served with Original dough, and the size is set automatically by set. Half & Half adds only 1,000 won to the set price.',item:{pizza:'Pizza',pasta:'Pasta',cola:'Cola',sideOne:'1 side',chicken:'Chicken'},card:{two:{badge:'Recommended for 2',title:'2-person Set',size:'Regular only',desc:'Pizza + pasta + small drink'},three:{badge:'Recommended for 3',title:'3-person Set',size:'Large only',desc:'Pizza + 1 side + large drink'},four:{badge:'Most popular',title:'4-person Set',size:'Family only',desc:'Pizza + 2 sides + large drink'}}}},
    pickup:{title:'Choose your takeout pickup time',subtitle:'Order now or reserve a pickup time for today.',now:'Order now',nowDesc:'Order now and pick up when it is ready.',reserve:'Reserve pickup',reserveDesc:'Choose your preferred pickup time today.',closed:'Reservations for today are closed.',reserveTitle:'Choose a pickup reservation time',reserveGuide:'Reservations are available in 10-minute intervals from at least 30 minutes after now.',hour:'Hour',minute:'Minute',hourUnit:':00',minuteUnit:' min',selectedTime:'Selected time',confirm:'Confirm reservation time',noAvailableTime:'No reservation times are available today.',chooseNow:'Please choose Order now.',changeTime:'Choose order time again'},
    party:{title:'Select the number of guests',guide:'Use − or + to adjust the number, then continue.',count:'{count} {unit}',personUnit:'guests',range:'Minimum 1 · Maximum 16 guests',roomAvailable:'ROOM is available.',roomMinimum:'Rooms are available for groups of 6 or more.',outdoorOnly:'Groups of 13–16 can use outdoor seating only.',areaGuide:'Available areas are shown based on your party size and current seats.',next:'Next →',decrease:'Decrease guests',increase:'Increase guests'},
    seat:{areaTitle:'Choose a dining area',areaGuide:'All areas are shown. Unavailable areas are grayed out; tap them to see why.',fullWaitlist:'Full · Join waitlist',availableSeats:'{count} seats available',currentUnavailable:'Currently unavailable',policyTitle:'Seat hours guide',policyGuide:'Papa Zone · Outdoor: Daily 11:00–21:00 (last order 20:30)<br>PapaBottle · ROOM: Weekdays 11:00–14:00 / Saturday 15:00–21:00 with alcohol order (last order 20:30) / Closed Sunday',occupancyNote:'If an area is full, you can join the waitlist from an occupied table.',selectSeat:'Choose a seat in {area}',seatGuide:'Please select {count} table(s). You can only choose seats in the selected area.',queueCount:'{count} teams waiting',queueButton:'Join waitlist for this seat',summaryReady:'✓ Seat selection complete',summaryPrompt:'Please select a seat',summaryDetail:'Selected tables {selected} / {needed} · Total {seats} seats',personSeat:'{count}-person seat',selectedName:'{name} selected',area:{papaZone:'Papa Zone',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'Outdoor'},status:{available:'Available',selected:'Selected',occupied:'In use',unavailable:'Unavailable'},type:{twoPerson:'Couple seat',barTable:'4-person bar table',room:'ROOM',outdoorTable:'Outdoor table'},hours:{daily:'Daily 11:00–21:00 · Last order 20:30',limited:'Weekdays 11:00–14:00 · Saturday 15:00–21:00 with alcohol order · Closed Sunday'},reason:{beforeOpenDaily:'Not open yet. Available from 11:00 AM.',lastOrderClosed:'Last order has closed. (20:30)',closedToday:'Seating is closed for today.',availableNow:'Available now.',sundayClosed:'Closed on Sundays.',weekdayBeforeOpen:'Weekday seating starts at 11:00 AM.',weekdayClosed:'Weekday seating ends at 14:00.',weekdayAvailable:'Available weekdays 11:00–14:00.',saturdayBeforeOpen:'On Saturday, available from 15:00 for alcohol-order customers only.',alcoholOnly:'Available for alcohol-order customers only.',genericUnavailable:'Currently unavailable.',partyUnavailable:'This area is not available for {count} guests.'},rule:{twoOrLess:'You can select {count} table(s) in Papa Zone couple/bar seats, PapaBottle tables 1/4, or Outdoor.',fourOrLess:'You can select {count} table(s) in Papa Zone bar seats, PapaBottle tables 2/3, or Outdoor.',five:'You can select {count} table(s) at PapaBottle tables 2/3 or Outdoor.',roomOrOutdoor:'You can select {count} table(s) in ROOM or Outdoor.',outdoorOnly:'Groups of 13–16 must select {count} table(s) in Outdoor.'},desc:{coupleBar:'Couple seat · Bar table',barTable:'Bar table',annexSmall:'Tables 1 · 4',annexMedium:'Tables 2 · 3',unavailable:'Unavailable',roomTables:'Select {count} 4-person table(s)',outdoorTables:'Select {count} 4-person table(s)'}},

    dough:{name:{hand:'Hand-tossed dough',thin:'Thin crust'},desc:{hand:'Chewy, savory original dough',thin:'Crispy texture with toppings up front'}},
    size:{name:{r:'R Regular',l:'L Large',f:'F Family'},desc:{r:'23 cm · 1–2 people',l:'31 cm · 2–3 people',f:'36 cm · 3–4 people'}},
    crust:{name:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'},desc:{오리지널:'Classic chewy, savory crust',치즈롤:'String cheese and cheddar baked into the edge',골드링:'Sweet potato mousse with string cheese'},sizeLabel:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'}},
    topping:{priceLabel:'{price}','t0':{name:'Extra Cheese',desc:'Extra Cheese',category:'Topping'},'t1':{name:'3 Blend Cheese',desc:'3 Blend Cheese',category:'Topping'},'t2':{name:'2 Blend Cheese',desc:'2 Blend Cheese',category:'Topping'},'t3':{name:'Bacon',desc:'Bacon',category:'Topping'},'t4':{name:'Beef',desc:'Beef',category:'Topping'},'t5':{name:'Chicken',desc:'Chicken',category:'Topping'},'t6':{name:'Italian Sausage',desc:'Italian Sausage',category:'Topping'},'t7':{name:'Ham',desc:'Ham',category:'Topping'},'t8':{name:'Pepperoni',desc:'Pepperoni',category:'Topping'},'t9':{name:'Tomato',desc:'Tomato',category:'Topping'},'t10':{name:'Potato',desc:'Potato',category:'Topping'},'t11':{name:'Corn',desc:'Corn',category:'Topping'},'t12':{name:'Pineapple',desc:'Pineapple',category:'Topping'},'t13':{name:'Black Olive',desc:'Black Olive',category:'Topping'},'t14':{name:'Jalapeño',desc:'Jalapeño',category:'Topping'},'t15':{name:'Onion',desc:'Onion',category:'Topping'},'t16':{name:'Green Pepper',desc:'Green Pepper',category:'Topping'},'t17':{name:'Mushroom',desc:'Mushroom',category:'Topping'}},
    side:{includedLabel:'Included in set',priceLabel:'{price}','wings':{name:'Papa Wings',desc:'Papa Wings',category:'Side'},'strips':{name:'Chicken Strips',desc:'Chicken Strips',category:'Side'},'cheesesticks':{name:'Cheese Sticks',desc:'Cheese Sticks',category:'Side'},'baconsticks':{name:'Bacon Cheese Sticks',desc:'Bacon Cheese Sticks',category:'Side'},'meatpasta':{name:'Meat Sauce Pasta',desc:'Meat Sauce Pasta',category:'Side'},'whitepasta':{name:'White Sauce Pasta',desc:'White Sauce Pasta',category:'Side'},'rosepasta':{name:'Rosé Pasta',desc:'Rosé Pasta',category:'Side'},'breadsticks':{name:'Bread Sticks',desc:'Bread Sticks',category:'Side'},'corn':{name:'Papa Corn Salad',desc:'Papa Corn Salad',category:'Side'},'coleslaw':{name:'Papa Coleslaw',desc:'Papa Coleslaw',category:'Side'},'brownie':{name:'Double Chocolate Chip Brownie',desc:'Double Chocolate Chip Brownie',category:'Side'}},
    language:{title:'Choose your language',subtitle:'Select the language to use during this session.'},
    drink:{singleTitle:'Water & bottled beer',includedLabel:'Included in set',priceLabel:'{price}',group:{coke:'Coca-Cola',cokeZero:'Coca-Cola Zero',sprite:'Sprite',spriteZero:'Sprite Zero',water:'Water',beer:'Beer',other:'Other'},'coke-500':{name:'Coca-Cola',desc:'Coca-Cola',category:'Drink',variant:'Coca-Cola'},'coke-zero-500':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'Drink',variant:'Coca-Cola Zero'},'sprite-500':{name:'Sprite',desc:'Sprite',category:'Drink',variant:'Sprite'},'sprite-zero-500':{name:'Sprite Zero',desc:'Sprite Zero',category:'Drink',variant:'Sprite Zero'},'coke-125':{name:'Coca-Cola',desc:'Coca-Cola',category:'Drink',variant:'Coca-Cola'},'coke-zero-15':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'Drink',variant:'Coca-Cola Zero'},'sprite-15':{name:'Sprite',desc:'Sprite',category:'Drink',variant:'Sprite'},'sprite-zero-15':{name:'Sprite Zero',desc:'Sprite Zero',category:'Drink',variant:'Sprite Zero'},'water-500':{name:'Water 500ml',desc:'Water 500ml',category:'Drink',variant:'Water 500ml'},'budweiser-bottle':{name:'Budweiser Bottle Beer',desc:'Budweiser Bottle Beer',category:'Drink',variant:'Budweiser Bottle Beer'}},
    cart:{title:'Cart',subtitle:'Add a set, UP & UP, or a single item, or continue with your order.',confirmRemove:'Remove this item from your cart?',empty:'Your cart is empty',totalPayment:'Total due',addSet:'Add set',addUpUp:'Add UP & UP',addSingle:'Add single item',orderNow:'Order now',remove:'Remove',singlePizza:'Whole pizza',halfPizza:'Half & Half',setName:'Set for {count}',additionalOrder:'Additional order',notSelected:'No pizza selected yet',reservationTimeMissing:'Time not selected',toppingCount:'Toppings {count}',sideCount:'Sides {count}',drinkCount:'Drinks {count}'},
    review:{title:'Review Order',subtitle:'Review your pizza, add-ons, and discounts.',confirmOrder:'Confirm order',confirmNote:'Please confirm the order details and amount before continuing.',includedInSet:'Included in set',included:'Included',additionalToppings:'Extra toppings',includedSides:'Included sides',includedDrinks:'Included drinks',additionalSides:'Extra sides',additionalDrinks:'Extra drinks & sauces',halfPizza:'Half & Half'},
    orderSummary:{normalAmount:'Regular item total',totalDiscount:'Total discount',finalPayment:'Final total'},
    unit:{quantity:'× {count}'},
    pizza:{'P001':{name:'Super Papa’s'},'P002':{name:'John’s Favorite'},'P003':{name:'All Meat'},'P004':{name:'Spicy Chicken Ranch'},'P005':{name:'Irish Potato'},'P006':{name:'Chicken BBQ'},'P007':{name:'Ham Mushroom Six Cheese'},'P008':{name:'Premium Grilled Bulgogi'},'P009':{name:'Six Cheese'},'P010':{name:'Spicy Italian'},'P011':{name:'THIN Shrimp Alfredo'},'P012':{name:'Margherita'},'P013':{name:'Pepperoni'},'P014':{name:'Hawaiian'},'P015':{name:'Garden Special'},noPizzaTitle:'No pizza',noPizzaStrong:'Order without pizza',noPizzaDesc:'You can order only sides and drinks.'},
    nav:{home:'Start over',previous:'Previous',next:'Next'},
    phone:{title:'Enter your phone number',subtitle:'010 is fixed. Please enter the remaining 8 digits.',clear:'Clear all',orderNumber:'Order number (last 4 digits):',invalid:'Please enter the last 8 digits correctly.',next:'Select payment method'},
    done:{title:'Your order has been received',orderLabel:'Order number · last 4 digits of phone',paymentRequired:'Please pay by {payment} at the counter',paymentGuide:'Pizza making starts after payment is complete.',reserveTime:'Reservation time {time}',guide:'Please check your order number and come to the counter.',home:'Start over'}
  };
