window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.ja={
    meta:{htmlLang:'ja',title:'パパジョンズ モバイルキオスク V13'},
    inactivity:{title:'注文を続けますか？',body:'まもなく注文内容が自動的にリセットされます。',guide:'注文を続けるには、下のボタンを押してください。',continue:'注文を続ける',home:'最初に戻る',seconds:'秒'},
    labels:{orderType:{takeout:'お持ち帰り',dinein:'店内飲食'},promo:{normal:'Regular Order',takeout:'Takeout 20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'Set Menu'},dough:{original:'Original',thin:'Thin Crust',croissant:'Croissant'},crust:{original:'Original',cheeseRoll:'Cheese Roll',goldRing:'Gold Ring',thin:'Thin Crust',croissant:'Croissant'},size:{R:'レギュラーサイズ',L:'ラージサイズ',F:'ファミリーサイズ'},payment:{cash:'現金',card:'クレジットカード',meal_ticket:'食券デジャン',bizle:'Bizle食券'}},
    home:{location:'パパジョンズ 板橋第2テクノバレー店',headlinePrefix:'今日も',headlineAccent:'焼きたて',headlineSuffix:'ピザをお楽しみください！',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'店内飲食',dineInFeatureMeal:'ゆったり店内でお食事',dineInFeatureSeats:'さまざまな座席',dineInFeatureSet:'セットメニュー注文',takeoutTitle:'お持ち帰り',takeoutFeatureFast:'早くて簡単なお持ち帰り',takeoutFeatureReady:'すぐにお持ち帰り可能',takeoutFeatureBenefit:'割引特典',happyHourDeal:'Rサイズピザ 15,000ウォン',takeoutDeal:'L/F お持ち帰り20%割引',takeoutDealDesc:'お持ち帰り割引で今すぐ注文',takeoutSizeNote:'ラージサイズ以上',takeoutDiscountRate:'20%割引'},
    orderType:{title:'ご利用方法を選択してください'},
    benefit:{title:'注文タイプを選択してください',subtitle:{dinein:'セットメニュー、UP & UP、通常注文から選択してください。',takeout:'ご希望の特典を選択してください。'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UPはLサイズ販売ピザ専用です。Lサイズの価格で決済し、Fサイズと選択したクラストへ無料アップグレードされます。'},card:{set:{title:'セットメニュー',desc:'2名 · 3名 · 4名',pill:'人数に合わせた充実セット'},upup:{title:'UP & UP',desc:'ラージ注文でファミリーにアップグレード',pill:'クラストまで無料'},normal:{title:'通常注文',desc:'お好みのメニューとオプションを選択',pill:'自由に注文',sideDrinkOnlyDesc:'サイドメニューとドリンクだけでも注文できます。'},happy:{title:'HAPPY HOUR',desc:'16:00〜20:00 Rサイズ',pill:'15,000ウォン'},takeout:{title:'お持ち帰り20%',desc:'L/Fピザお持ち帰り',pill:'20%割引'}},setChoice:{title:'セットメニューを選択してください',subtitle:'人数に合った内容を確認してセットを選択してください。',select:'選択する →',note:'セットメニューはオリジナル生地で提供され、セットに応じてサイズが自動適用されます。ハーフ&ハーフ選択時はセット金額に1,000ウォンのみ追加されます。',item:{pizza:'ピザ',pasta:'パスタ',cola:'コーラ',sideOne:'サイド1品',chicken:'チキン'},card:{two:{badge:'2名おすすめ',title:'2名セット',size:'レギュラー専用',desc:'ピザ + パスタ + 小さいドリンク'},three:{badge:'3名おすすめ',title:'3名セット',size:'ラージ専用',desc:'ピザ + サイド1品 + 大きいドリンク'},four:{badge:'一番人気',title:'4名セット',size:'ファミリー専用',desc:'ピザ + サイド2品 + 大きいドリンク'}}}},
    pickup:{title:'お持ち帰りの受け取り時間を選択してください',subtitle:'今すぐ注文するか、本日の受け取り時間を予約できます。',now:'今すぐ注文',nowDesc:'今すぐ注文し、準備でき次第お受け取りください。',reserve:'予約注文',reserveDesc:'本日の希望受け取り時間を選択します。',closed:'本日予約可能な時間は終了しました。',reserveTitle:'受け取り予約時間を選択してください',reserveGuide:'現在時刻から30分後以降、10分単位で予約できます。',hour:'時間',minute:'分',hourUnit:'時',minuteUnit:'分',selectedTime:'選択時間',confirm:'予約時間を確定',noAvailableTime:'本日予約可能な時間がありません。',chooseNow:'今すぐ注文を選択してください。',changeTime:'注文時間を再選択'},
    party:{title:'ご利用人数を選択してください',guide:'− または + ボタンで人数を調整して次へ進んでください。',count:'{count}{unit}',personUnit:'名',range:'最少1名 · 最大16名',roomAvailable:'ROOMを選択できます。',roomMinimum:'ルームは6名以上から選択できます。',outdoorOnly:'13〜16名は屋外席のみ選択できます。',areaGuide:'人数と現在の空席に合わせて利用可能なエリアが表示されます。',next:'次へ →',decrease:'人数を減らす',increase:'人数を増やす'},
    seat:{areaTitle:'食事エリアを選択してください',areaGuide:'すべてのエリアを表示します。現在利用できないエリアは選択不可として表示され、タップすると理由を確認できます。',fullWaitlist:'満席 · 順番待ち可能',availableSeats:'{count}席利用可能',currentUnavailable:'現在選択不可',policyTitle:'座席利用案内',policyGuide:'パパゾーン·屋外席: 毎日 11:00〜21:00（ラストオーダー20:30）<br>PapaBottle·ROOM: 平日の午前11時から午後2時までのみ利用できます。土日・祝日は利用できません。',occupancyNote:'満席エリアを選択すると、使用中のテーブルで順番待ちを登録できます。',selectSeat:'{area} 席選択',seatGuide:'{count}個のテーブルを選択してください。選択したエリア内でのみ席を選べます。',queueCount:'待ち {count}組',queueButton:'この席で順番待ち',summaryReady:'✓ 座席選択完了',summaryPrompt:'座席を選択してください',summaryDetail:'選択テーブル {selected} / {needed} · 合計 {seats}席',personSeat:'{count}人席',selectedName:'{name} 選択済み',area:{papaZone:'パパゾーン',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'屋外席'},status:{available:'利用可能',selected:'選択済み',occupied:'使用中',unavailable:'利用不可'},type:{twoPerson:'カップル席',barTable:'4人バーテーブル',room:'ROOM',outdoorTable:'屋外テーブル'},hours:{daily:'毎日 11:00〜21:00 · ラストオーダー 20:30',limited:'平日 11:00〜14:00 営業 · 土日・祝日は利用不可'},reason:{beforeOpenDaily:'現在は利用時間前です。午前11時から利用できます。',lastOrderClosed:'ラストオーダーは終了しました。（20:30）',closedToday:'本日の座席利用は終了しました。',availableNow:'現在利用できます。',sundayClosed:'日曜日は営業していません。',weekdayBeforeOpen:'平日は午前11時から利用できます。',weekdayClosed:'平日の座席利用は14:00に終了します。',weekdayAvailable:'平日 11:00〜14:00 利用できます。',genericUnavailable:'現在利用できません。',partyUnavailable:'{count}名の利用規定上、選択できないエリアです。'},rule:{twoOrLess:'パパゾーンのカップル席・バーテーブル、PapaBottle 1番・4番、屋外ゾーンから{count}卓を選択できます。',fourOrLess:'パパゾーンのバーテーブル、PapaBottle 2番・3番、屋外ゾーンから{count}卓を選択できます。',five:'PapaBottle 2番・3番または屋外ゾーンから{count}卓を選択できます。',roomOrOutdoor:'ROOMまたは屋外ゾーンから{count}卓を選択できます。',outdoorOnly:'13〜16名は屋外ゾーンで{count}卓を選択してください。'},desc:{coupleBar:'カップル席 · バーテーブル',barTable:'バーテーブル',annexSmall:'1番 · 4番',annexMedium:'2番 · 3番',unavailable:'利用不可',roomTables:'4名テーブルを{count}卓選択',outdoorTables:'4名テーブルを{count}卓選択'}},

    dough:{name:{hand:'Original',thin:'Thin Crust'},desc:{hand:'もちもちで香ばしい基本生地',thin:'サクサク食感でトッピングを楽しめます'}},
    size:{name:{r:'R レギュラー',l:'L ラージ',f:'F ファミリー'},desc:{r:'23cm · 1〜2人',l:'31cm · 2〜3人',f:'36cm · 3〜4人'}},
    crust:{name:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'},desc:{오리지널:'もちもちで香ばしい定番クラスト',치즈롤:'縁にストリングチーズとチェダー入り',골드링:'甘いさつまいもムースとチーズ'},sizeLabel:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'}},
    topping:{priceLabel:'{price}','t0':{name:'Extra Cheese',desc:'Extra Cheese',category:'トッピング'},'t1':{name:'3 Blend Cheese',desc:'3 Blend Cheese',category:'トッピング'},'t2':{name:'2 Blend Cheese',desc:'2 Blend Cheese',category:'トッピング'},'t3':{name:'Bacon',desc:'Bacon',category:'トッピング'},'t4':{name:'Beef',desc:'Beef',category:'トッピング'},'t5':{name:'Chicken',desc:'Chicken',category:'トッピング'},'t6':{name:'Italian Sausage',desc:'Italian Sausage',category:'トッピング'},'t7':{name:'Ham',desc:'Ham',category:'トッピング'},'t8':{name:'Pepperoni',desc:'Pepperoni',category:'トッピング'},'t9':{name:'Tomato',desc:'Tomato',category:'トッピング'},'t10':{name:'Potato',desc:'Potato',category:'トッピング'},'t11':{name:'Corn',desc:'Corn',category:'トッピング'},'t12':{name:'Pineapple',desc:'Pineapple',category:'トッピング'},'t13':{name:'Black Olive',desc:'Black Olive',category:'トッピング'},'t14':{name:'Jalapeño',desc:'Jalapeño',category:'トッピング'},'t15':{name:'Onion',desc:'Onion',category:'トッピング'},'t16':{name:'Green Pepper',desc:'Green Pepper',category:'トッピング'},'t17':{name:'Mushroom',desc:'Mushroom',category:'トッピング'}},
    side:{includedLabel:'セット込み',priceLabel:'{price}','wings':{name:'Papa\'s Wings',desc:'Papa\'s Wings',category:'サイド'},'strips':{name:'Chicken Strips',desc:'Chicken Strips',category:'サイド'},'cheesesticks':{name:'Cheese Sticks',desc:'Cheese Sticks',category:'サイド'},'baconsticks':{name:'Bacon Cheese Sticks',desc:'Bacon Cheese Sticks',category:'サイド'},'meatpasta':{name:'Meat Sauce Pasta',desc:'Meat Sauce Pasta',category:'サイド'},'whitepasta':{name:'White Sauce Pasta',desc:'White Sauce Pasta',category:'サイド'},'rosepasta':{name:'Rosé Pasta',desc:'Rosé Pasta',category:'サイド'},'breadsticks':{name:'Bread Sticks',desc:'Bread Sticks',category:'サイド'},'corn':{name:'Papa Corn Salad',desc:'Papa Corn Salad',category:'サイド'},'coleslaw':{name:'Papa Coleslaw',desc:'Papa Coleslaw',category:'サイド'},'brownie':{name:'Double Chocolate Chip Brownie',desc:'Double Chocolate Chip Brownie',category:'サイド'}},
    language:{title:'言語を選択してください',subtitle:'このセッションで使用する言語を選択してください。'},
    drink:{singleTitle:'水・瓶ビール',includedLabel:'セット込み',priceLabel:'{price}',group:{coke:'コカ・コーラ',cokeZero:'コカ・コーラ ゼロ',sprite:'スプライト',spriteZero:'スプライト ゼロ',water:'Water',beer:'Beer',other:'Other'},'coke-500':{name:'Coca-Cola',desc:'Coca-Cola',category:'ドリンク',variant:'Coca-Cola'},'coke-zero-500':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'ドリンク',variant:'Coca-Cola Zero'},'sprite-500':{name:'Sprite',desc:'Sprite',category:'ドリンク',variant:'Sprite'},'sprite-zero-500':{name:'Sprite Zero',desc:'Sprite Zero',category:'ドリンク',variant:'Sprite Zero'},'coke-125':{name:'Coca-Cola',desc:'Coca-Cola',category:'ドリンク',variant:'Coca-Cola'},'coke-zero-15':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'ドリンク',variant:'Coca-Cola Zero'},'sprite-15':{name:'Sprite',desc:'Sprite',category:'ドリンク',variant:'Sprite'},'sprite-zero-15':{name:'Sprite Zero',desc:'Sprite Zero',category:'ドリンク',variant:'Sprite Zero'},'water-500':{name:'Water 500ml',desc:'Water 500ml',category:'ドリンク',variant:'Water 500ml'},'budweiser-bottle':{name:'Budweiser Bottle Beer',desc:'Budweiser Bottle Beer',category:'ドリンク',variant:'Budweiser Bottle Beer'}},
    cart:{title:'カート',subtitle:'セット・UP & UP・単品を追加するか、注文へ進んでください。',confirmRemove:'この商品をカートから削除しますか？',empty:'カートは空です',totalPayment:'お支払い予定額',addMoreTitle:'追加注文',addSet:'セットメニューを追加',addUpUp:'UP & UPを追加',addSingle:'単品を追加',continueCheckout:'追加せずに注文確定へ進めます。',orderNow:'注文する',remove:'削除',singlePizza:'1枚',halfPizza:'ハーフ＆ハーフ',setName:'{count}人セット',additionalOrder:'追加注文',notSelected:'ピザがまだ選択されていません',reservationTimeMissing:'時間未選択',toppingCount:'トッピング {count}個',sideCount:'サイド {count}個',drinkCount:'ドリンク {count}個'},
    review:{title:'注文内容の確認',subtitle:'ピザの内容、追加メニュー、割引金額をご確認ください。',confirmOrder:'注文を確定',confirmNote:'注文内容と金額を確認してから押してください。',includedInSet:'セットに含まれます',included:'含む',additionalToppings:'追加トッピング',includedSides:'セットのサイド',includedDrinks:'セットのドリンク',additionalSides:'追加サイド',additionalDrinks:'追加ドリンク・ソース',halfPizza:'ハーフ＆ハーフ',doughTypeLabel:'生地タイプ',sizeLabel:'サイズ',crustTypeLabel:'クラストタイプ',compositionLabel:'ピザ構成',pizzaToppingLabel:'ピザトッピング',toppingAddTitle:'トッピング追加',pizzaBaseAmount:'{size}ピザ基本料金',crustExtraAmount:'{crust}追加料金',halfExtraAmount:'ハーフ＆ハーフ追加料金',toppingExtraAmount:'トッピング追加料金',normalSubtotal:'通常合計',benefitDiscount:'{benefit}割引',pizzaFinalAmount:'ピザ支払金額',setNormalAmount:'セット通常金額',setDiscountAmount:'セット割引金額',setFinalAmount:'セット適用金額'},
    orderSummary:{normalAmount:'商品の通常金額',totalDiscount:'割引合計',finalPayment:'最終お支払い額'},
    unit:{quantity:'× {count}'},
    pizza:{'P001':{name:'Super Papa\'s'},'P002':{name:'John\'s Favorite'},'P003':{name:'All Meat'},'P004':{name:'Spicy Chicken Ranch'},'P005':{name:'Irish Potato'},'P006':{name:'Chicken BBQ'},'P007':{name:'Ham Mushroom Six Cheese'},'P008':{name:'Premium Grilled Bulgogi'},'P009':{name:'Six Cheese'},'P010':{name:'Spicy Italian'},'P011':{name:'THIN Shrimp Alfredo'},'P012':{name:'Margherita'},'P013':{name:'Pepperoni'},'P014':{name:'Hawaiian'},'P015':{name:'Garden Special'},noPizzaTitle:'選択なし',noPizzaStrong:'ピザなしで注文',noPizzaDesc:'サイドメニューとドリンクだけでも注文できます。'},
    nav:{home:'最初へ',previous:'戻る',next:'次へ'},
    phone:{title:'電話番号を入力してください',subtitle:'010は固定です。残り8桁を入力してください。',clear:'すべて削除',orderNumber:'注文番号（電話番号下4桁）:',invalid:'電話番号の下8桁を正しく入力してください。',next:'決済方法を選択'},
    customerName:{title:'お呼びするお名前を入力してください',subtitle:'ご注文の準備ができたら、このお名前でお呼びします。',label:'お名前またはニックネーム',keyboard:'画面キーボード',shift:'大文字・小文字',space:'スペース',clear:'すべて削除',confirm:'確認',invalid:'1〜20文字で入力してください。',ready:'入力済み ({count}/20)'},
    done:{title:'注文を受け付けました',orderLabel:'注文番号・電話番号下4桁',paymentRequired:'カウンターで{payment}にてお支払いください',paymentMethodPhrase:{cash:'現金',card:'クレジットカード',meal_ticket:'食券台帳',bizle:'ゼロペイ'},paymentGuide:'お支払い完了後、ピザの調理を開始します。',reserveTime:'予約時間 {time}',guide:'注文番号をご確認のうえ、カウンターまでお越しください。',home:'最初へ'}
  };
Object.assign(window.PJ_I18N_LOCALES.ja.review,{resetTitle:'最初に戻る',resetBody:'現在の注文内容はすべて削除されます。最初の画面に戻りますか？',resetCancel:'キャンセル',resetConfirm:'最初に戻る'});
window.PJ_I18N_LOCALES.ja.party.label='人数';
Object.assign(window.PJ_I18N_LOCALES.ja.drink.group,{coke:'Coca-Cola',cokeZero:'Coca-Cola Zero',sprite:'Sprite',spriteZero:'Sprite Zero'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.set,{title:'Set Menu'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.normal,{title:'Regular Order'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.takeout,{title:'Takeout 20%'});
Object.assign(window.PJ_I18N_LOCALES.ja.review,{orderListLabel:'注文商品一覧',paginationLabel:'注文内容ページ',previousItems:'前の注文内容',nextItems:'次の注文内容'});
Object.assign(window.PJ_I18N_LOCALES.ja.seat,{capacity:{full:'満席',twoFull:'2人席満席',fourFull:'4人席満席',fullDescription:'現在の人数では着席できません',queue:'順番待ち',closed:'営業時間終了',unavailable:'利用不可',review:'確認が必要',phoneGuide:'連絡先の携帯電話番号を入力してください。',phoneLabel:'順番待ちの携帯電話番号',keypadLabel:'電話番号テンキー',clear:'全削除',backspace:'1文字削除',cancel:'キャンセル',register:'登録',submitting:'登録中',phoneInvalid:'010から始まる11桁の番号を入力してください。',registerFailed:'順番待ちを登録できませんでした。もう一度お試しください。'}});
Object.assign(window.PJ_I18N_LOCALES.ja.seat,{area:{papaZone:'パパゾーン',annex:'別館',privateRoom:'別館団体席',outdoor:'屋外席'},policyGuide:'パパゾーン・屋外席：毎日11:00〜21:00（ラストオーダー20:30）<br>別館・別館団体席：平日11:00〜14:00のみ。土日・祝日は利用できません。',name:{papaCouple:'パパゾーン カップル席',papaBar:'パパゾーン バーテーブル席',annex1:'別館1',annex2:'別館2',annex3:'別館3',annex4:'別館4',room1:'団体席1',room2:'団体席2',room3:'団体席3',outdoor1:'屋外席1',outdoor2:'屋外席2',outdoor3:'屋外席3',outdoor4:'屋外席4'},areaLocation:{papa:'パパジョンズ店内の座席です。',annex:'パパジョンズ隣のPapaBottle座席スペースです。',room:'別館内の団体席です。',outdoor:'パパジョンズの屋外席です。'},location:{papaCouple:'パパジョンズ店内の2人席です。',papaBar:'パパジョンズ店内のバーテーブル席です。',annex1:'窓側にある2人席です。',annex2:'造り付けベンチのある座席です。',annex3:'カウンター横の座席です。',annex4:'ワイン棚のすぐ横にある2人席です。',room1:'カーテン前のテーブルです。',room2:'ストーブ前のテーブルです。',room3:'飾り棚前のテーブルです。',outdoor:'屋外エリアにある座席です。'}});
Object.assign(window.PJ_I18N_LOCALES.ja.party,{roomAvailable:'別館団体席を選択できます。',roomMinimum:'別館団体席は6名以上から選択できます。'});
Object.assign(window.PJ_I18N_LOCALES.ja.home,{happyHourSize:'Rサイズ',happyHourPrice:'₩15,000',happyHourTakeoutOnly:'お持ち帰り注文限定',happyHourDineInExclusion:'店内飲食には適用されません。'});
window.PJ_I18N_LOCALES.ja.voice={language:'ご利用になる言語を選択してください。',home:'店内飲食またはお持ち帰りを選択してください。ハッピーアワーはお持ち帰り注文限定です。',orderType:'店内飲食またはお持ち帰りを選択してください。',timing:'すぐに注文するか、受取時間を予約できます。',party:'ご利用人数を選択してください。',area:'ご利用になる座席エリアを選択してください。',full:'現在の人数で利用できる座席がありません。順番待ちをご利用ください。',closed:'この座席エリアの営業時間は終了しました。',table:'座席位置の案内を確認し、ご利用になる座席を選択してください。',waitlistPhone:'携帯電話番号を入力してください。座席の準備ができ次第お知らせします。',benefit:'適用する割引または注文特典を選択してください。',set:'人数に合ったセットメニューを選択してください。',pizza:'ご注文のピザを選択してください。',secondPizza:'2枚目のピザを選択してください。',size:'ピザのサイズを選択してください。',crust:'生地とクラストを選択し、追加料金をご確認ください。',toppingPrompt:'トッピングを追加しますか？',toppingSelect:'追加するトッピングを選び、次へを押してください。',includedSide:'セットに含まれるサイドメニューを選択してください。',extraSide:'追加で注文するサイドメニューを選択してください。',includedDrink:'セットに含まれるドリンクを選択してください。',extraDrink:'追加で注文するドリンクを選択してください。',accompaniment:'追加で必要なソースや付け合わせを選択してください。',review:'注文内容、数量、割引額、最終支払額をご確認ください。',disposables:'使い捨てフォークが必要か選択してください。',phone:'携帯電話番号を入力してください。',customerName:'お名前を入力してください。',payment:'お支払い方法を選択してください。',reserveTime:'受取時間を選択してください。',submit:'注文内容が正しければ、注文ボタンを押してください。',completeNormal:'注文番号{orderNo}を受け付けました。お支払い完了後に調理を開始します。カウンターへお越しください。',completeForeign:'{customerName}様、ご注文を受け付けました。お支払い完了後に調理を開始します。カウンターへお越しください。',completeReservationPrepaid:'予約注文番号{orderNo}を受け付けました。受取予約時間の15分前から調理を開始します。',completeReservationPostpaid:'予約注文番号{orderNo}を受け付けました。受取予約時間の15分前から調理を開始します。受取時にカウンターでお支払いください。',completeReservationForeignPrepaid:'{customerName}様、予約注文を受け付けました。受取予約時間の15分前から調理を開始します。',completeReservationForeignPostpaid:'{customerName}様、予約注文を受け付けました。受取予約時間の15分前から調理を開始します。受取時にカウンターでお支払いください。',error:'注文を送信できませんでした。スタッフをお呼びください。',inactivity:'まもなく注文画面がリセットされます。注文を続ける場合は「注文を続ける」を押してください。'};
Object.assign(window.PJ_I18N_LOCALES.ja.seat,{type:{...window.PJ_I18N_LOCALES.ja.seat.type,room:'別館団体席'},rule:{twoOrLess:'パパゾーンのカップル席・バーテーブル席、別館1・4、屋外席から{count}卓を選択できます。',fourOrLess:'パパゾーンのバーテーブル席、別館2・3、屋外席から{count}卓を選択できます。',five:'別館2・3または屋外席から{count}卓を選択できます。',roomOrOutdoor:'別館・別館団体席・屋外席から{count}卓を選択できます。',outdoorOnly:'13〜16名は屋外席で{count}卓を選択してください。'},desc:{...window.PJ_I18N_LOCALES.ja.seat.desc,roomTables:'団体席を{count}卓選択',outdoorTables:'屋外テーブルを{count}卓選択'}});
