window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.ja={
    meta:{htmlLang:'ja',title:'パパジョンズ モバイルキオスク V13'},
    labels:{orderType:{takeout:'お持ち帰り',dinein:'店内飲食'},promo:{normal:'Regular Order',takeout:'Takeout 20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'Set Menu'},dough:{original:'Original',thin:'Thin Crust',croissant:'Croissant'},crust:{original:'Original',cheeseRoll:'Cheese Roll',goldRing:'Gold Ring',thin:'Thin Crust',croissant:'Croissant'},size:{R:'レギュラーサイズ',L:'ラージサイズ',F:'ファミリーサイズ'},payment:{cash:'現金',card:'クレジットカード',meal_ticket:'食券デジャン',bizle:'Bizle食券'}},
    home:{location:'パパジョンズ 板橋第2テクノバレー店',headlinePrefix:'今日も',headlineAccent:'焼きたて',headlineSuffix:'ピザをお楽しみください！',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'店内飲食',dineInFeatureMeal:'ゆったり店内でお食事',dineInFeatureSeats:'さまざまな座席',dineInFeatureSet:'セットメニュー注文',takeoutTitle:'お持ち帰り',takeoutFeatureFast:'早くて簡単なお持ち帰り',takeoutFeatureReady:'すぐにお持ち帰り可能',takeoutFeatureBenefit:'割引特典',happyHourDeal:'Rサイズピザ 15,000ウォン',takeoutDeal:'L/F お持ち帰り20%割引',takeoutDealDesc:'お持ち帰り割引で今すぐ注文',beerTitle:'ピザとビールもOK！',beerHeineken:'Heineken 生ビール 8,000ウォン',beerBudweiser:'Budweiser 瓶ビール 5,000ウォン'},
    orderType:{title:'ご利用方法を選択してください'},
    benefit:{title:'注文タイプを選択してください',subtitle:{dinein:'セットメニュー、UP & UP、通常注文から選択してください。',takeout:'ご希望の特典を選択してください。'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UPはLサイズ販売ピザ専用です。Lサイズの価格で決済し、Fサイズと選択したクラストへ無料アップグレードされます。'},card:{set:{title:'セットメニュー',desc:'2名 · 3名 · 4名',pill:'人数に合わせた充実セット'},upup:{title:'UP & UP',desc:'ラージ注文でファミリーにアップグレード',pill:'クラストまで無料'},normal:{title:'通常注文',desc:'お好みのメニューとオプションを選択',pill:'自由に注文',sideDrinkOnlyDesc:'サイドメニューとドリンクだけでも注文できます。'},happy:{title:'HAPPY HOUR',desc:'16:00〜20:00 Rサイズ',pill:'15,000ウォン'},takeout:{title:'お持ち帰り20%',desc:'L/Fピザお持ち帰り',pill:'20%割引'}},setChoice:{title:'セットメニューを選択してください',subtitle:'人数に合った内容を確認してセットを選択してください。',select:'選択する →',note:'セットメニューはオリジナル生地で提供され、セットに応じてサイズが自動適用されます。ハーフ&ハーフ選択時はセット金額に1,000ウォンのみ追加されます。',item:{pizza:'ピザ',pasta:'パスタ',cola:'コーラ',sideOne:'サイド1品',chicken:'チキン'},card:{two:{badge:'2名おすすめ',title:'2名セット',size:'レギュラー専用',desc:'ピザ + パスタ + 小さいドリンク'},three:{badge:'3名おすすめ',title:'3名セット',size:'ラージ専用',desc:'ピザ + サイド1品 + 大きいドリンク'},four:{badge:'一番人気',title:'4名セット',size:'ファミリー専用',desc:'ピザ + サイド2品 + 大きいドリンク'}}}},
    pickup:{title:'お持ち帰りの受け取り時間を選択してください',subtitle:'今すぐ注文するか、本日の受け取り時間を予約できます。',now:'今すぐ注文',nowDesc:'今すぐ注文し、準備でき次第お受け取りください。',reserve:'予約注文',reserveDesc:'本日の希望受け取り時間を選択します。',closed:'本日予約可能な時間は終了しました。',reserveTitle:'受け取り予約時間を選択してください',reserveGuide:'現在時刻から30分後以降、10分単位で予約できます。',hour:'時間',minute:'分',hourUnit:'時',minuteUnit:'分',selectedTime:'選択時間',confirm:'予約時間を確定',noAvailableTime:'本日予約可能な時間がありません。',chooseNow:'今すぐ注文を選択してください。',changeTime:'注文時間を再選択'},
    party:{title:'ご利用人数を選択してください',guide:'− または + ボタンで人数を調整して次へ進んでください。',count:'{count}{unit}',personUnit:'名',range:'最少1名 · 最大16名',roomAvailable:'ROOMを選択できます。',roomMinimum:'ルームは6名以上から選択できます。',outdoorOnly:'13〜16名は屋外席のみ選択できます。',areaGuide:'人数と現在の空席に合わせて利用可能なエリアが表示されます。',next:'次へ →',decrease:'人数を減らす',increase:'人数を増やす'},
    seat:{areaTitle:'食事エリアを選択してください',areaGuide:'すべてのエリアを表示します。現在利用できないエリアはグレーで表示され、タップすると理由を確認できます。',fullWaitlist:'満席 · 順番待ち可能',availableSeats:'{count}席利用可能',currentUnavailable:'現在選択不可',policyTitle:'座席利用案内',policyGuide:'パパゾーン·屋外席: 毎日 11:00〜21:00（ラストオーダー20:30）<br>PapaBottle·ROOM: 平日11:00〜14:00 / 土曜15:00〜21:00 酒類利用時可能（ラストオーダー20:30）/ 日曜休み',occupancyNote:'満席エリアを選択すると、使用中のテーブルで順番待ちを登録できます。',selectSeat:'{area} 席選択',seatGuide:'{count}個のテーブルを選択してください。選択したエリア内でのみ席を選べます。',queueCount:'待ち {count}組',queueButton:'この席で順番待ち',summaryReady:'✓ 座席選択完了',summaryPrompt:'座席を選択してください',summaryDetail:'選択テーブル {selected} / {needed} · 合計 {seats}席',personSeat:'{count}人席',selectedName:'{name} 選択済み',area:{papaZone:'パパゾーン',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'屋外席'},status:{available:'利用可能',selected:'選択済み',occupied:'使用中',unavailable:'利用不可'},type:{twoPerson:'カップル席',barTable:'4人バーテーブル',room:'ROOM',outdoorTable:'屋外テーブル'},hours:{daily:'毎日 11:00〜21:00 · ラストオーダー 20:30',limited:'平日 11:00〜14:00 · 土曜 15:00〜21:00（アルコール注文時） · 日曜休業'},reason:{beforeOpenDaily:'現在は利用時間前です。午前11時から利用できます。',lastOrderClosed:'ラストオーダーは終了しました。（20:30）',closedToday:'本日の座席利用は終了しました。',availableNow:'現在利用できます。',sundayClosed:'日曜日は営業していません。',weekdayBeforeOpen:'平日は午前11時から利用できます。',weekdayClosed:'平日の座席利用は14:00に終了します。',weekdayAvailable:'平日 11:00〜14:00 利用できます。',saturdayBeforeOpen:'土曜日は15:00からアルコール注文のお客様のみ利用できます。',alcoholOnly:'アルコール注文のお客様のみ利用できます。',genericUnavailable:'現在利用できません。',partyUnavailable:'{count}名の利用規定上、選択できないエリアです。'},rule:{twoOrLess:'パパゾーンのカップル席・バーテーブル、PapaBottle 1番・4番、屋外ゾーンから{count}卓を選択できます。',fourOrLess:'パパゾーンのバーテーブル、PapaBottle 2番・3番、屋外ゾーンから{count}卓を選択できます。',five:'PapaBottle 2番・3番または屋外ゾーンから{count}卓を選択できます。',roomOrOutdoor:'ROOMまたは屋外ゾーンから{count}卓を選択できます。',outdoorOnly:'13〜16名は屋外ゾーンで{count}卓を選択してください。'},desc:{coupleBar:'カップル席 · バーテーブル',barTable:'バーテーブル',annexSmall:'1番 · 4番',annexMedium:'2番 · 3番',unavailable:'利用不可',roomTables:'4名テーブルを{count}卓選択',outdoorTables:'4名テーブルを{count}卓選択'}},

    dough:{name:{hand:'Original',thin:'Thin Crust'},desc:{hand:'もちもちで香ばしい基本生地',thin:'サクサク食感でトッピングを楽しめます'}},
    size:{name:{r:'R レギュラー',l:'L ラージ',f:'F ファミリー'},desc:{r:'23cm · 1〜2人',l:'31cm · 2〜3人',f:'36cm · 3〜4人'}},
    crust:{name:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'},desc:{오리지널:'もちもちで香ばしい定番クラスト',치즈롤:'縁にストリングチーズとチェダー入り',골드링:'甘いさつまいもムースとチーズ'},sizeLabel:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'}},
    topping:{priceLabel:'{price}','t0':{name:'Extra Cheese',desc:'Extra Cheese',category:'トッピング'},'t1':{name:'3 Blend Cheese',desc:'3 Blend Cheese',category:'トッピング'},'t2':{name:'2 Blend Cheese',desc:'2 Blend Cheese',category:'トッピング'},'t3':{name:'Bacon',desc:'Bacon',category:'トッピング'},'t4':{name:'Beef',desc:'Beef',category:'トッピング'},'t5':{name:'Chicken',desc:'Chicken',category:'トッピング'},'t6':{name:'Italian Sausage',desc:'Italian Sausage',category:'トッピング'},'t7':{name:'Ham',desc:'Ham',category:'トッピング'},'t8':{name:'Pepperoni',desc:'Pepperoni',category:'トッピング'},'t9':{name:'Tomato',desc:'Tomato',category:'トッピング'},'t10':{name:'Potato',desc:'Potato',category:'トッピング'},'t11':{name:'Corn',desc:'Corn',category:'トッピング'},'t12':{name:'Pineapple',desc:'Pineapple',category:'トッピング'},'t13':{name:'Black Olive',desc:'Black Olive',category:'トッピング'},'t14':{name:'Jalapeño',desc:'Jalapeño',category:'トッピング'},'t15':{name:'Onion',desc:'Onion',category:'トッピング'},'t16':{name:'Green Pepper',desc:'Green Pepper',category:'トッピング'},'t17':{name:'Mushroom',desc:'Mushroom',category:'トッピング'}},
    side:{includedLabel:'セット込み',priceLabel:'{price}','wings':{name:'Papa\'s Wings',desc:'Papa\'s Wings',category:'サイド'},'strips':{name:'Chicken Strips',desc:'Chicken Strips',category:'サイド'},'cheesesticks':{name:'Cheese Sticks',desc:'Cheese Sticks',category:'サイド'},'baconsticks':{name:'Bacon Cheese Sticks',desc:'Bacon Cheese Sticks',category:'サイド'},'meatpasta':{name:'Meat Sauce Pasta',desc:'Meat Sauce Pasta',category:'サイド'},'whitepasta':{name:'White Sauce Pasta',desc:'White Sauce Pasta',category:'サイド'},'rosepasta':{name:'Rosé Pasta',desc:'Rosé Pasta',category:'サイド'},'breadsticks':{name:'Bread Sticks',desc:'Bread Sticks',category:'サイド'},'corn':{name:'Papa Corn Salad',desc:'Papa Corn Salad',category:'サイド'},'coleslaw':{name:'Papa Coleslaw',desc:'Papa Coleslaw',category:'サイド'},'brownie':{name:'Double Chocolate Chip Brownie',desc:'Double Chocolate Chip Brownie',category:'サイド'}},
    language:{title:'言語を選択してください',subtitle:'このセッションで使用する言語を選択してください。'},
    drink:{singleTitle:'水・瓶ビール',includedLabel:'セット込み',priceLabel:'{price}',group:{coke:'コカ・コーラ',cokeZero:'コカ・コーラ ゼロ',sprite:'スプライト',spriteZero:'スプライト ゼロ',water:'Water',beer:'Beer',other:'Other'},'coke-500':{name:'Coca-Cola',desc:'Coca-Cola',category:'ドリンク',variant:'Coca-Cola'},'coke-zero-500':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'ドリンク',variant:'Coca-Cola Zero'},'sprite-500':{name:'Sprite',desc:'Sprite',category:'ドリンク',variant:'Sprite'},'sprite-zero-500':{name:'Sprite Zero',desc:'Sprite Zero',category:'ドリンク',variant:'Sprite Zero'},'coke-125':{name:'Coca-Cola',desc:'Coca-Cola',category:'ドリンク',variant:'Coca-Cola'},'coke-zero-15':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'ドリンク',variant:'Coca-Cola Zero'},'sprite-15':{name:'Sprite',desc:'Sprite',category:'ドリンク',variant:'Sprite'},'sprite-zero-15':{name:'Sprite Zero',desc:'Sprite Zero',category:'ドリンク',variant:'Sprite Zero'},'water-500':{name:'Water 500ml',desc:'Water 500ml',category:'ドリンク',variant:'Water 500ml'},'budweiser-bottle':{name:'Budweiser Bottle Beer',desc:'Budweiser Bottle Beer',category:'ドリンク',variant:'Budweiser Bottle Beer'}},
    cart:{title:'カート',subtitle:'セット・UP & UP・単品を追加するか、注文へ進んでください。',confirmRemove:'この商品をカートから削除しますか？',empty:'カートは空です',totalPayment:'お支払い予定額',addMoreTitle:'追加注文',addSet:'セットメニューを追加',addUpUp:'UP & UPを追加',addSingle:'単品を追加',continueCheckout:'追加せずに注文確定へ進めます。',orderNow:'注文する',remove:'削除',singlePizza:'1枚',halfPizza:'ハーフ＆ハーフ',setName:'{count}人セット',additionalOrder:'追加注文',notSelected:'ピザがまだ選択されていません',reservationTimeMissing:'時間未選択',toppingCount:'トッピング {count}個',sideCount:'サイド {count}個',drinkCount:'ドリンク {count}個'},
    review:{title:'注文内容の確認',subtitle:'ピザの内容、追加メニュー、割引金額をご確認ください。',confirmOrder:'注文を確定',confirmNote:'注文内容と金額を確認してから押してください。',includedInSet:'セットに含まれます',included:'含む',additionalToppings:'追加トッピング',includedSides:'セットのサイド',includedDrinks:'セットのドリンク',additionalSides:'追加サイド',additionalDrinks:'追加ドリンク・ソース',halfPizza:'ハーフ＆ハーフ'},
    orderSummary:{normalAmount:'商品の通常金額',totalDiscount:'割引合計',finalPayment:'最終お支払い額'},
    unit:{quantity:'× {count}'},
    pizza:{'P001':{name:'Super Papa\'s'},'P002':{name:'John\'s Favorite'},'P003':{name:'All Meat'},'P004':{name:'Spicy Chicken Ranch'},'P005':{name:'Irish Potato'},'P006':{name:'Chicken BBQ'},'P007':{name:'Ham Mushroom Six Cheese'},'P008':{name:'Premium Grilled Bulgogi'},'P009':{name:'Six Cheese'},'P010':{name:'Spicy Italian'},'P011':{name:'THIN Shrimp Alfredo'},'P012':{name:'Margherita'},'P013':{name:'Pepperoni'},'P014':{name:'Hawaiian'},'P015':{name:'Garden Special'},noPizzaTitle:'選択なし',noPizzaStrong:'ピザなしで注文',noPizzaDesc:'サイドメニューとドリンクだけでも注文できます。'},
    nav:{home:'最初へ',previous:'戻る',next:'次へ'},
    phone:{title:'電話番号を入力してください',subtitle:'010は固定です。残り8桁を入力してください。',clear:'すべて削除',orderNumber:'注文番号（電話番号下4桁）:',invalid:'電話番号の下8桁を正しく入力してください。',next:'決済方法を選択'},
    done:{title:'注文を受け付けました',orderLabel:'注文番号・電話番号下4桁',paymentRequired:'カウンターで{payment}にてお支払いください',paymentGuide:'お支払い完了後、ピザの調理を開始します。',reserveTime:'予約時間 {time}',guide:'注文番号をご確認のうえ、カウンターまでお越しください。',home:'最初へ'}
  };
window.PJ_I18N_LOCALES.ja.party.label='人数';
Object.assign(window.PJ_I18N_LOCALES.ja.drink.group,{coke:'Coca-Cola',cokeZero:'Coca-Cola Zero',sprite:'Sprite',spriteZero:'Sprite Zero'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.set,{title:'Set Menu'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.normal,{title:'Regular Order'});
Object.assign(window.PJ_I18N_LOCALES.ja.benefit.card.takeout,{title:'Takeout 20%'});
