window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.ko={
    meta:{htmlLang:'ko',title:'파파존스 모바일 키오스크 kiosk V13'},
    labels:{
      orderType:{takeout:'포장',dinein:'먹고가기'},
      promo:{normal:'일반주문',takeout:'포장 20%',happy:'해피아워',upup:'UP & UP',set:'세트메뉴'},
      dough:{original:'클래식',thin:'씬도우',croissant:'크루아상'},
      crust:{original:'오리지널',cheeseRoll:'치즈롤',goldRing:'골드링',thin:'씬도우',croissant:'크루아상'},
      size:{R:'레귤러사이즈',L:'라지사이즈',F:'패밀리사이즈'},
      payment:{cash:'현금',card:'신용카드',meal_ticket:'식권대장',bizle:'비즐식권'}
    },
    home:{
      location:'판교2테크노밸리점',headlinePrefix:'오늘도 ',headlineAccent:'갓 구운',headlineSuffix:' 피자를 즐겨보세요!',tagline:'Better Ingredients. Better Pizza.',
      dineInTitle:'먹고가기',dineInFeatureMeal:'편안한 매장 식사',dineInFeatureSeats:'다양한 좌석',dineInFeatureSet:'세트 메뉴 주문',
      takeoutTitle:'포장하기',takeoutFeatureFast:'빠르고 간편한 포장',takeoutFeatureReady:'바로 포장 가능',takeoutFeatureBenefit:'할인 혜택',
      happyHourDeal:'R 사이즈 피자 15,000원',takeoutDeal:'L/F 포장 20% 할인',takeoutDealDesc:'포장 할인으로 바로 주문',takeoutSizeNote:'라지사이즈 이상',takeoutDiscountRate:'20% 할인',beerTitle:'피맥 가능!',beerHeineken:'하이네켄 생맥주 8,000원',beerBudweiser:'버드와이저 병맥주 5,000원'
    },
    orderType:{title:'어떻게 이용하시나요?'},
    benefit:{title:'주문 유형을 선택해 주세요',subtitle:{dinein:'세트메뉴, UP & UP, 일반주문 중 선택해 주세요.',takeout:'원하는 혜택을 선택해 주세요.'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP은 L 사이즈 판매 피자 전용이며, L 피자 가격으로 결제하고 F 사이즈와 선택 크러스트로 무료 업그레이드됩니다.'},card:{set:{title:'세트메뉴',desc:'2인 · 3인 · 4인',pill:'인원에 맞춘 알찬 구성'},upup:{title:'UP & UP',desc:'라지 주문 시 패밀리 업그레이드',pill:'크러스트까지 무료'},normal:{title:'일반주문',desc:'원하는 메뉴와 옵션 선택',pill:'자유롭게 주문',sideDrinkOnlyDesc:'사이드·음료만 주문 가능'},happy:{title:'해피아워',desc:'16:00~20:00 R 사이즈',pill:'15,000원'},takeout:{title:'포장 20%',desc:'L/F 피자 포장',pill:'20% 할인'}},setChoice:{title:'세트메뉴를 선택해 주세요',subtitle:'인원에 맞는 구성을 확인한 뒤 세트를 선택해 주세요.',select:'선택하기 →',note:'세트메뉴는 클래식 도우로 제공되며, 세트에 따라 사이즈가 자동 적용됩니다. 반반 선택 시 세트 금액에 1,000원만 추가됩니다.',item:{pizza:'피자',pasta:'파스타',cola:'콜라',sideOne:'사이드 1종',chicken:'치킨'},card:{two:{badge:'2인 추천',title:'2인 세트',size:'레귤러 전용',desc:'피자 + 파스타 + 작은 음료'},three:{badge:'3인 추천',title:'3인 세트',size:'라지 전용',desc:'피자 + 사이드 1종 + 큰 음료'},four:{badge:'가장 인기',title:'4인 세트',size:'패밀리 전용',desc:'피자 + 사이드 2종 + 큰 음료'}}}},
    pickup:{title:'포장 주문 시간을 선택해 주세요',subtitle:'바로 주문하거나 오늘 픽업할 시간을 예약할 수 있습니다.',now:'바로 주문',nowDesc:'지금 주문하고 준비되는 대로 픽업합니다.',reserve:'예약 주문',reserveDesc:'오늘 원하는 픽업 시간을 선택합니다.',closed:'오늘 예약 가능한 시간이 마감되었습니다.',reserveTitle:'픽업 예약 시간을 선택해 주세요',reserveGuide:'현재 시각에서 최소 30분 이후부터 10분 단위로 예약할 수 있습니다.',hour:'시간',minute:'분',hourUnit:'시',minuteUnit:'분',selectedTime:'선택 시간',confirm:'예약 시간 확정',noAvailableTime:'오늘 예약 가능한 시간이 없습니다.',chooseNow:'바로 주문을 선택해 주세요.',changeTime:'주문 시간 다시 선택'},
    party:{title:'이용 인원을 선택해 주세요',guide:'− 또는 + 버튼으로 인원을 조정한 뒤 다음으로 이동하세요.',count:'{count}{unit}',personUnit:'명',range:'최소 1명 · 최대 16명',roomAvailable:'ROOM을 선택할 수 있습니다.',roomMinimum:'룸은 최초 6명 이상부터 선택할 수 있습니다.',outdoorOnly:'13~16명은 야외존만 선택할 수 있습니다.',areaGuide:'인원수와 현재 빈자리에 맞춰 이용 가능한 구역이 표시됩니다.',next:'다음 →',decrease:'인원 줄이기',increase:'인원 늘리기'},
    seat:{areaTitle:'식사 구역을 선택해 주세요',areaGuide:'모든 구역을 표시합니다. 현재 이용할 수 없는 구역은 회색으로 표시되며, 누르면 이용 사유를 확인할 수 있습니다.',fullWaitlist:'만석 · 줄서기 가능',availableSeats:'{count}석 이용 가능',currentUnavailable:'현재 선택 불가',policyTitle:'좌석 운영 안내',policyGuide:'파파존·야외존: 매일 11:00~21:00 (라스트오더 20:30)<br>보틀존·보틀룸존: 평일 11:00~14:00 / 토요일 15:00~21:00 주류 이용 시 가능 (라스트오더 20:30) / 일요일 휴무',occupancyNote:'만석 구역을 선택하면 사용 중인 테이블에서 줄서기를 등록할 수 있습니다.',selectSeat:'{area} 자리 선택',seatGuide:'{count}개의 테이블을 선택해 주세요. 선택한 구역 안에서만 좌석을 고를 수 있습니다.',queueCount:'대기 {count}팀',queueButton:'이 좌석 줄서기',summaryReady:'✓ 좌석 선택 완료',summaryPrompt:'좌석을 선택해 주세요',summaryDetail:'선택 테이블 {selected} / {needed} · 총 {seats}석',personSeat:'{count}인석',selectedName:'{name} 선택됨',area:{papaZone:'파파존',annex:'보틀존',privateRoom:'보틀룸존',outdoor:'야외존'},status:{available:'사용가능',selected:'주문중',occupied:'사용중',unavailable:'이용 불가'},type:{twoPerson:'커플석',barTable:'4인 바테이블',room:'ROOM',outdoorTable:'야외 테이블'},hours:{daily:'매일 11:00~21:00 · 라스트오더 20:30',limited:'평일 11:00~14:00 · 토요일 15:00~21:00(주류 이용 시) · 일요일 휴무'},reason:{beforeOpenDaily:'현재 이용 전입니다. 오전 11시부터 이용 가능합니다.',lastOrderClosed:'라스트오더가 마감되었습니다. (20:30)',closedToday:'오늘 좌석 이용이 종료되었습니다.',availableNow:'현재 이용 가능합니다.',sundayClosed:'일요일은 운영하지 않습니다.',weekdayBeforeOpen:'평일은 오전 11시부터 이용 가능합니다.',weekdayClosed:'평일 좌석 이용은 14:00에 종료됩니다.',weekdayAvailable:'평일 11:00~14:00 이용 가능합니다.',saturdayBeforeOpen:'토요일은 15:00부터 주류 주문 고객만 이용 가능합니다.',alcoholOnly:'주류 주문 고객만 이용 가능합니다.',genericUnavailable:'현재 이용할 수 없습니다.',partyUnavailable:'{count}명 이용 규정상 선택할 수 없는 구역입니다.'},rule:{twoOrLess:'파파존 커플석·바테이블, 보틀존 1번·4번, 야외존에서 {count}개를 선택할 수 있습니다.',fourOrLess:'파파존 바테이블, 보틀존 2번·3번, 야외존에서 {count}개를 선택할 수 있습니다.',five:'보틀존 2번·3번 또는 야외존에서 {count}개를 선택할 수 있습니다.',roomOrOutdoor:'보틀룸존 또는 야외존에서 {count}개를 선택할 수 있습니다.',outdoorOnly:'13~16명은 야외존에서 {count}개를 선택해야 합니다.'},desc:{coupleBar:'커플석 · 바테이블',barTable:'바테이블',annexSmall:'1번 · 4번',annexMedium:'2번 · 3번',unavailable:'이용 불가',roomTables:'4인 테이블 {count}개 선택',outdoorTables:'4인 테이블 {count}개 선택'}},

    dough:{name:{hand:'수타도우',thin:'씬도우'},desc:{hand:'쫄깃하고 고소한 기본 도우',thin:'바삭한 식감, 더욱 풍부한 토핑'}},
    size:{name:{r:'R 레귤러',l:'L 라지',f:'F 패밀리'},desc:{r:'23cm · 1~2인',l:'31cm · 2~3인',f:'36cm · 3~4인'}},
    crust:{name:{오리지널:'오리지널',치즈롤:'치즈롤',골드링:'골드링'},desc:{오리지널:'쫄깃하고 고소한 기본에 충실한 맛',치즈롤:'도우 속 스트링 치즈와 체다 치즈의 풍미',골드링:'달콤한 고구마 무스와 스트링 치즈의 만남'},sizeLabel:{오리지널:'오리지널',치즈롤:'치즈롤',골드링:'골드링'}},
    topping:{priceLabel:'{price}','t0':{name:'엑스트라 치즈',desc:'엑스트라 치즈',category:'토핑'},'t1':{name:'3블렌드 치즈',desc:'3블렌드 치즈',category:'토핑'},'t2':{name:'2블렌드 치즈',desc:'2블렌드 치즈',category:'토핑'},'t3':{name:'베이컨',desc:'베이컨',category:'토핑'},'t4':{name:'비프',desc:'비프',category:'토핑'},'t5':{name:'치킨',desc:'치킨',category:'토핑'},'t6':{name:'이탈리안 소시지',desc:'이탈리안 소시지',category:'토핑'},'t7':{name:'햄',desc:'햄',category:'토핑'},'t8':{name:'페퍼로니',desc:'페퍼로니',category:'토핑'},'t9':{name:'토마토',desc:'토마토',category:'토핑'},'t10':{name:'포테이토',desc:'포테이토',category:'토핑'},'t11':{name:'콘',desc:'콘',category:'토핑'},'t12':{name:'파인애플',desc:'파인애플',category:'토핑'},'t13':{name:'블랙 올리브',desc:'블랙 올리브',category:'토핑'},'t14':{name:'할라피뇨',desc:'할라피뇨',category:'토핑'},'t15':{name:'양파',desc:'양파',category:'토핑'},'t16':{name:'청피망',desc:'청피망',category:'토핑'},'t17':{name:'양송이',desc:'양송이',category:'토핑'}},
    side:{includedLabel:'세트 포함',priceLabel:'{price}','wings':{name:'파파스윙',desc:'파파스윙',category:'사이드'},'strips':{name:'치킨스트립',desc:'치킨스트립',category:'사이드'},'cheesesticks':{name:'치즈스틱',desc:'치즈스틱',category:'사이드'},'baconsticks':{name:'베이컨치즈스틱',desc:'베이컨치즈스틱',category:'사이드'},'meatpasta':{name:'미트소스파스타',desc:'미트소스파스타',category:'사이드'},'whitepasta':{name:'화이트소스파스타',desc:'화이트소스파스타',category:'사이드'},'rosepasta':{name:'로제파스타',desc:'로제파스타',category:'사이드'},'breadsticks':{name:'브레드스틱',desc:'브레드스틱',category:'사이드'},'corn':{name:'파파 콘샐러드',desc:'파파 콘샐러드',category:'사이드'},'coleslaw':{name:'파파 코울슬로',desc:'파파 코울슬로',category:'사이드'},'brownie':{name:'더블 초코칩 브라우니',desc:'더블 초코칩 브라우니',category:'사이드'}},
    language:{title:'언어를 선택해 주세요',subtitle:'주문 중 사용할 언어를 선택하세요.'},
    drink:{singleTitle:'생수·병맥주',includedLabel:'세트 포함',priceLabel:'{price}',group:{coke:'코카-콜라',cokeZero:'코카-콜라 제로',sprite:'스프라이트',spriteZero:'스프라이트 제로',water:'Water',beer:'Beer',other:'Other'},'coke-500':{name:'코카콜라',desc:'코카콜라',category:'음료',variant:'코카콜라'},'coke-zero-500':{name:'코카콜라 제로',desc:'코카콜라 제로',category:'음료',variant:'코카콜라 제로'},'sprite-500':{name:'스프라이트',desc:'스프라이트',category:'음료',variant:'스프라이트'},'sprite-zero-500':{name:'스프라이트 제로',desc:'스프라이트 제로',category:'음료',variant:'스프라이트 제로'},'coke-125':{name:'코카콜라',desc:'코카콜라',category:'음료',variant:'코카콜라'},'coke-zero-15':{name:'코카콜라 제로',desc:'코카콜라 제로',category:'음료',variant:'코카콜라 제로'},'sprite-15':{name:'스프라이트',desc:'스프라이트',category:'음료',variant:'스프라이트'},'sprite-zero-15':{name:'스프라이트 제로',desc:'스프라이트 제로',category:'음료',variant:'스프라이트 제로'},'water-500':{name:'생수 500ml',desc:'생수 500ml',category:'음료',variant:'생수 500ml'},'budweiser-bottle':{name:'버드와이저 병맥주',desc:'버드와이저 병맥주',category:'음료',variant:'버드와이저 병맥주'}},
    cart:{title:'장바구니',subtitle:'세트·UP & UP 또는 단품을 추가하거나 주문을 진행해 주세요.',confirmRemove:'상품을 장바구니에서 삭제하시겠습니까?',empty:'장바구니가 비어 있습니다',totalPayment:'총 결제금액',addMoreTitle:'추가 주문',addSet:'세트메뉴 추가',addUpUp:'UP & UP 추가',addSingle:'단품 추가',continueCheckout:'추가하지 않고 주문 확정을 계속할 수 있습니다.',orderNow:'주문하기',remove:'삭제',singlePizza:'한판',halfPizza:'반반',setName:'{count}인 세트',additionalOrder:'추가 주문',notSelected:'아직 피자를 선택하지 않았습니다',reservationTimeMissing:'시간 미선택',toppingCount:'토핑 {count}개',sideCount:'사이드 {count}개',drinkCount:'음료 {count}개'},
    review:{title:'주문 내용 확인',subtitle:'피자 구성, 추가 메뉴, 할인 금액을 확인해 주세요.',confirmOrder:'주문 확정',confirmNote:'주문 내역과 금액을 확인한 후 눌러주세요.',includedInSet:'세트 포함',included:'포함',additionalToppings:'추가 토핑',includedSides:'세트 포함 사이드',includedDrinks:'세트 포함 음료',additionalSides:'추가 사이드',additionalDrinks:'추가 음료·소스',halfPizza:'반반피자'},
    orderSummary:{normalAmount:'상품 정상금액',totalDiscount:'총 할인',finalPayment:'최종 결제금액'},
    unit:{quantity:'× {count}'},
    pizza:{'P001':{name:'수퍼 파파스'},'P002':{name:'존스 페이버릿'},'P003':{name:'올미트'},'P004':{name:'스파이시 치킨랜치'},'P005':{name:'아이리쉬 포테이토'},'P006':{name:'치킨 바베큐'},'P007':{name:'햄 머쉬룸 식스 치즈'},'P008':{name:'프리미엄 직화불고기'},'P009':{name:'식스 치즈'},'P010':{name:'스파이시 이탈리안'},'P011':{name:'THIN 슈림프 알프레도'},'P012':{name:'마가리타'},'P013':{name:'페퍼로니'},'P014':{name:'하와이안'},'P015':{name:'가든 스페셜'},noPizzaTitle:'선택안함',noPizzaStrong:'피자 없이 주문',noPizzaDesc:'사이드 메뉴와 음료만 주문도 가능합니다.'},
    nav:{home:'처음으로',previous:'이전',next:'다음'},
    phone:{title:'전화번호를 입력해 주세요',subtitle:'010은 고정입니다. 뒤 8자리를 모두 입력해 주세요.',clear:'전체삭제',orderNumber:'주문번호(전화번호 뒤 4자리):',invalid:'전화번호 뒤 8자리를 정확히 입력해 주세요.',next:'결제수단 선택'},
    done:{title:'주문이 접수되었습니다',orderLabel:'주문번호 · 전화번호 뒤 4자리',paymentRequired:'{payment}로 카운터에서 결제해 주세요',paymentGuide:'결제 완료 후 피자 제조가 시작됩니다.',reserveTime:'예약시간 {time}',guide:'주문번호를 확인하시고 카운터로 와 주세요.',home:'처음으로'}
  };
