window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.vi={
    meta:{htmlLang:'vi',title:'Kiosk di động Papa John\'s V13'},
    labels:{orderType:{takeout:'Mang đi',dinein:'Ăn tại chỗ'},promo:{normal:'Regular Order',takeout:'Takeout 20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'Set Menu'},dough:{original:'Original',thin:'Thin Crust',croissant:'Croissant'},crust:{original:'Original',cheeseRoll:'Cheese Roll',goldRing:'Gold Ring',thin:'Thin Crust',croissant:'Croissant'},size:{R:'Cỡ Regular',L:'Cỡ Large',F:'Cỡ Family'},payment:{cash:'Tiền mặt',card:'Thẻ tín dụng',meal_ticket:'Meal Ticket',bizle:'Bizle Meal Ticket'}},
    home:{location:'Papa John\'s Pangyo 2 Techno Valley',headlinePrefix:'Hôm nay hãy thưởng thức pizza ',headlineAccent:'mới nướng',headlineSuffix:'!',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'Ăn tại chỗ',dineInFeatureMeal:'Dùng bữa thoải mái tại cửa hàng',dineInFeatureSeats:'Nhiều lựa chọn chỗ ngồi',dineInFeatureSet:'Đặt set menu',takeoutTitle:'Mang đi',takeoutFeatureFast:'Mang đi nhanh và tiện',takeoutFeatureReady:'Có thể nhận nhanh',takeoutFeatureBenefit:'Ưu đãi giảm giá',happyHourDeal:'Pizza cỡ R 15,000 won',takeoutDeal:'L/F mang đi giảm 20%',takeoutDealDesc:'Đặt ngay với ưu đãi mang đi',beerTitle:'Có pizza & bia!',beerHeineken:'Bia tươi Heineken 8,000 won',beerBudweiser:'Bia chai Budweiser 5,000 won'},
    orderType:{title:'Bạn muốn dùng như thế nào?'},
    benefit:{title:'Chọn loại ưu đãi',subtitle:{dinein:'Chọn Set Menu, UP & UP hoặc Đặt thường.',takeout:'Chọn ưu đãi bạn muốn.'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP chỉ áp dụng cho pizza có bán cỡ L. Thanh toán giá pizza cỡ L và nâng cấp miễn phí lên cỡ F cùng viền đã chọn.'},card:{set:{title:'Set menu',desc:'Cho 2 · 3 · 4 người',pill:'Combo đầy đủ theo số người'},upup:{title:'UP & UP',desc:'Đặt Large nâng lên Family',pill:'Miễn phí cả viền'},normal:{title:'Đặt thường',desc:'Chọn món và tùy chọn mong muốn',pill:'Đặt tự do'},happy:{title:'HAPPY HOUR',desc:'16:00–20:00 cỡ R',pill:'15,000 won'},takeout:{title:'Mang đi 20%',desc:'Pizza L/F mang đi',pill:'Giảm 20%'}},setChoice:{title:'Chọn set menu',subtitle:'Kiểm tra combo phù hợp số người rồi chọn set.',select:'Chọn →',note:'Set menu dùng đế nguyên bản và tự động áp dụng cỡ theo từng set. Chọn Half & Half chỉ cộng thêm 1,000 won vào giá set.',item:{pizza:'Pizza',pasta:'Pasta',cola:'Cola',sideOne:'1 món phụ',chicken:'Gà'},card:{two:{badge:'Gợi ý cho 2',title:'Set 2 người',size:'Chỉ Regular',desc:'Pizza + pasta + đồ uống nhỏ'},three:{badge:'Gợi ý cho 3',title:'Set 3 người',size:'Chỉ Large',desc:'Pizza + 1 món phụ + đồ uống lớn'},four:{badge:'Phổ biến nhất',title:'Set 4 người',size:'Chỉ Family',desc:'Pizza + 2 món phụ + đồ uống lớn'}}}},
    pickup:{title:'Chọn thời gian nhận đơn mang đi',subtitle:'Bạn có thể đặt ngay hoặc hẹn giờ nhận trong hôm nay.',now:'Đặt ngay',nowDesc:'Đặt ngay và nhận khi đơn đã sẵn sàng.',reserve:'Đặt hẹn giờ',reserveDesc:'Chọn thời gian nhận mong muốn trong hôm nay.',closed:'Hôm nay đã hết khung giờ đặt hẹn.',reserveTitle:'Chọn thời gian hẹn nhận',reserveGuide:'Có thể hẹn từ ít nhất 30 phút sau hiện tại, theo từng 10 phút.',hour:'Giờ',minute:'Phút',hourUnit:' giờ',minuteUnit:' phút',selectedTime:'Thời gian đã chọn',confirm:'Xác nhận thời gian hẹn',noAvailableTime:'Hôm nay không còn thời gian đặt hẹn.',chooseNow:'Vui lòng chọn Đặt ngay.',changeTime:'Chọn lại thời gian đặt'},
    party:{title:'Chọn số người dùng bữa',guide:'Dùng nút − hoặc + để điều chỉnh số người rồi tiếp tục.',count:'{count} {unit}',personUnit:'người',range:'Tối thiểu 1 người · Tối đa 16 người',roomAvailable:'Có thể chọn ROOM.',roomMinimum:'Phòng chỉ chọn được từ 6 người trở lên.',outdoorOnly:'Nhóm 13–16 người chỉ có thể chọn khu ngoài trời.',areaGuide:'Khu vực khả dụng sẽ hiển thị theo số người và chỗ trống hiện tại.',next:'Tiếp →',decrease:'Giảm số người',increase:'Tăng số người'},
    seat:{areaTitle:'Chọn khu vực dùng bữa',areaGuide:'Tất cả khu vực được hiển thị. Khu vực hiện không dùng được sẽ có màu xám; chạm để xem lý do.',fullWaitlist:'Hết chỗ · Có thể xếp hàng',availableSeats:'Có {count} chỗ',currentUnavailable:'Hiện không thể chọn',policyTitle:'Hướng dẫn chỗ ngồi',policyGuide:'Papa Zone · Ngoài trời: hằng ngày 11:00–21:00 (last order 20:30)<br>PapaBottle · ROOM: ngày thường 11:00–14:00 / thứ Bảy 15:00–21:00 khi dùng đồ uống có cồn (last order 20:30) / Chủ nhật nghỉ',occupancyNote:'Nếu khu vực đã đầy, bạn có thể đăng ký xếp hàng tại bàn đang sử dụng.',selectSeat:'Chọn chỗ ở {area}',seatGuide:'Vui lòng chọn {count} bàn. Chỉ có thể chọn chỗ trong khu vực đã chọn.',queueCount:'{count} nhóm đang chờ',queueButton:'Xếp hàng cho chỗ này',summaryReady:'✓ Đã chọn xong chỗ',summaryPrompt:'Vui lòng chọn chỗ',summaryDetail:'Bàn đã chọn {selected} / {needed} · Tổng {seats} chỗ',personSeat:'Ghế {count} người',selectedName:'Đã chọn {name}',area:{papaZone:'Papa Zone',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'Ngoài trời'},status:{available:'Có thể dùng',selected:'Đã chọn',occupied:'Đang dùng',unavailable:'Không khả dụng'},type:{twoPerson:'Ghế đôi',barTable:'Bàn bar 4 người',room:'ROOM',outdoorTable:'Bàn ngoài trời'},hours:{daily:'Hằng ngày 11:00–21:00 · Gọi món cuối 20:30',limited:'Ngày thường 11:00–14:00 · Thứ Bảy 15:00–21:00 khi gọi đồ uống có cồn · Chủ Nhật nghỉ'},reason:{beforeOpenDaily:'Chưa đến giờ phục vụ. Có thể dùng từ 11:00 sáng.',lastOrderClosed:'Đã hết giờ gọi món cuối. (20:30)',closedToday:'Khu ghế đã đóng cho hôm nay.',availableNow:'Hiện có thể dùng.',sundayClosed:'Chủ Nhật không hoạt động.',weekdayBeforeOpen:'Ngày thường bắt đầu từ 11:00 sáng.',weekdayClosed:'Khu ghế ngày thường kết thúc lúc 14:00.',weekdayAvailable:'Có thể dùng ngày thường 11:00–14:00.',saturdayBeforeOpen:'Thứ Bảy chỉ dành cho khách gọi đồ uống có cồn từ 15:00.',alcoholOnly:'Chỉ dành cho khách gọi đồ uống có cồn.',genericUnavailable:'Hiện không thể dùng.',partyUnavailable:'Khu vực này không khả dụng cho {count} khách.'},rule:{twoOrLess:'Bạn có thể chọn {count} bàn ở ghế đôi/bàn bar Papa Zone, bàn 1/4 PapaBottle hoặc khu ngoài trời.',fourOrLess:'Bạn có thể chọn {count} bàn ở bàn bar Papa Zone, bàn 2/3 PapaBottle hoặc khu ngoài trời.',five:'Bạn có thể chọn {count} bàn ở bàn 2/3 PapaBottle hoặc khu ngoài trời.',roomOrOutdoor:'Bạn có thể chọn {count} bàn ở ROOM hoặc khu ngoài trời.',outdoorOnly:'Nhóm 13–16 khách phải chọn {count} bàn ở khu ngoài trời.'},desc:{coupleBar:'Ghế đôi · Bàn bar',barTable:'Bàn bar',annexSmall:'Bàn 1 · 4',annexMedium:'Bàn 2 · 3',unavailable:'Không khả dụng',roomTables:'Chọn {count} bàn 4 người',outdoorTables:'Chọn {count} bàn 4 người'}},

    dough:{name:{hand:'Original',thin:'Thin Crust'},desc:{hand:'Đế cơ bản dai và thơm',thin:'Giòn mỏng, làm nổi bật topping'}},
    size:{name:{r:'R Thường',l:'L Lớn',f:'F Gia đình'},desc:{r:'23 cm · 1–2 người',l:'31 cm · 2–3 người',f:'36 cm · 3–4 người'}},
    crust:{name:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'},desc:{오리지널:'Viền bánh dai thơm cổ điển',치즈롤:'Viền có string cheese và cheddar',골드링:'Khoai lang ngọt cùng string cheese'},sizeLabel:{오리지널:'Original',치즈롤:'Cheese Roll',골드링:'Gold Ring'}},
    topping:{priceLabel:'{price}','t0':{name:'Extra Cheese',desc:'Extra Cheese',category:'Topping'},'t1':{name:'3 Blend Cheese',desc:'3 Blend Cheese',category:'Topping'},'t2':{name:'2 Blend Cheese',desc:'2 Blend Cheese',category:'Topping'},'t3':{name:'Bacon',desc:'Bacon',category:'Topping'},'t4':{name:'Beef',desc:'Beef',category:'Topping'},'t5':{name:'Chicken',desc:'Chicken',category:'Topping'},'t6':{name:'Italian Sausage',desc:'Italian Sausage',category:'Topping'},'t7':{name:'Ham',desc:'Ham',category:'Topping'},'t8':{name:'Pepperoni',desc:'Pepperoni',category:'Topping'},'t9':{name:'Tomato',desc:'Tomato',category:'Topping'},'t10':{name:'Potato',desc:'Potato',category:'Topping'},'t11':{name:'Corn',desc:'Corn',category:'Topping'},'t12':{name:'Pineapple',desc:'Pineapple',category:'Topping'},'t13':{name:'Black Olive',desc:'Black Olive',category:'Topping'},'t14':{name:'Jalapeño',desc:'Jalapeño',category:'Topping'},'t15':{name:'Onion',desc:'Onion',category:'Topping'},'t16':{name:'Green Pepper',desc:'Green Pepper',category:'Topping'},'t17':{name:'Mushroom',desc:'Mushroom',category:'Topping'}},
    side:{includedLabel:'Đã gồm trong set',priceLabel:'{price}','wings':{name:'Papa\'s Wings',desc:'Papa\'s Wings',category:'Món phụ'},'strips':{name:'Chicken Strips',desc:'Chicken Strips',category:'Món phụ'},'cheesesticks':{name:'Cheese Sticks',desc:'Cheese Sticks',category:'Món phụ'},'baconsticks':{name:'Bacon Cheese Sticks',desc:'Bacon Cheese Sticks',category:'Món phụ'},'meatpasta':{name:'Meat Sauce Pasta',desc:'Meat Sauce Pasta',category:'Món phụ'},'whitepasta':{name:'White Sauce Pasta',desc:'White Sauce Pasta',category:'Món phụ'},'rosepasta':{name:'Rosé Pasta',desc:'Rosé Pasta',category:'Món phụ'},'breadsticks':{name:'Bread Sticks',desc:'Bread Sticks',category:'Món phụ'},'corn':{name:'Papa Corn Salad',desc:'Papa Corn Salad',category:'Món phụ'},'coleslaw':{name:'Papa Coleslaw',desc:'Papa Coleslaw',category:'Món phụ'},'brownie':{name:'Double Chocolate Chip Brownie',desc:'Double Chocolate Chip Brownie',category:'Món phụ'}},
    language:{title:'Chọn ngôn ngữ',subtitle:'Chọn ngôn ngữ dùng trong phiên này.'},
    drink:{singleTitle:'Nước & bia chai',includedLabel:'Đã gồm trong set',priceLabel:'{price}',group:{coke:'Coca-Cola',cokeZero:'Coca-Cola Zero',sprite:'Sprite',spriteZero:'Sprite Zero',water:'Water',beer:'Beer',other:'Other'},'coke-500':{name:'Coca-Cola',desc:'Coca-Cola',category:'Đồ uống',variant:'Coca-Cola'},'coke-zero-500':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'Đồ uống',variant:'Coca-Cola Zero'},'sprite-500':{name:'Sprite',desc:'Sprite',category:'Đồ uống',variant:'Sprite'},'sprite-zero-500':{name:'Sprite Zero',desc:'Sprite Zero',category:'Đồ uống',variant:'Sprite Zero'},'coke-125':{name:'Coca-Cola',desc:'Coca-Cola',category:'Đồ uống',variant:'Coca-Cola'},'coke-zero-15':{name:'Coca-Cola Zero',desc:'Coca-Cola Zero',category:'Đồ uống',variant:'Coca-Cola Zero'},'sprite-15':{name:'Sprite',desc:'Sprite',category:'Đồ uống',variant:'Sprite'},'sprite-zero-15':{name:'Sprite Zero',desc:'Sprite Zero',category:'Đồ uống',variant:'Sprite Zero'},'water-500':{name:'Water 500ml',desc:'Water 500ml',category:'Đồ uống',variant:'Water 500ml'},'budweiser-bottle':{name:'Budweiser Bottle Beer',desc:'Budweiser Bottle Beer',category:'Đồ uống',variant:'Budweiser Bottle Beer'}},
    cart:{title:'Giỏ hàng',subtitle:'Thêm combo, UP & UP hoặc món lẻ, hoặc tiếp tục đặt món.',confirmRemove:'Xóa món này khỏi giỏ hàng?',empty:'Giỏ hàng đang trống',totalPayment:'Tổng thanh toán',addMoreTitle:'Gọi thêm',addSet:'Thêm combo',addUpUp:'Thêm UP & UP',addSingle:'Thêm món lẻ',continueCheckout:'Bạn có thể tiếp tục xác nhận đơn mà không cần gọi thêm.',orderNow:'Đặt món',remove:'Xóa',singlePizza:'Pizza nguyên bánh',halfPizza:'Half & Half',setName:'Combo {count} người',additionalOrder:'Đặt thêm',notSelected:'Chưa chọn pizza',reservationTimeMissing:'Chưa chọn giờ',toppingCount:'Topping {count}',sideCount:'Món ăn kèm {count}',drinkCount:'Đồ uống {count}'},
    review:{title:'Kiểm tra đơn hàng',subtitle:'Vui lòng kiểm tra pizza, món thêm và giảm giá.',confirmOrder:'Xác nhận đơn',confirmNote:'Hãy kiểm tra nội dung đơn và số tiền trước khi nhấn.',includedInSet:'Bao gồm trong combo',included:'Bao gồm',additionalToppings:'Topping thêm',includedSides:'Món kèm trong combo',includedDrinks:'Đồ uống trong combo',additionalSides:'Món ăn kèm thêm',additionalDrinks:'Đồ uống & sốt thêm',halfPizza:'Half & Half'},
    orderSummary:{normalAmount:'Tổng giá gốc',totalDiscount:'Tổng giảm giá',finalPayment:'Số tiền cuối cùng'},
    unit:{quantity:'× {count}'},
    pizza:{'P001':{name:'Super Papa\'s'},'P002':{name:'John\'s Favorite'},'P003':{name:'All Meat'},'P004':{name:'Spicy Chicken Ranch'},'P005':{name:'Irish Potato'},'P006':{name:'Chicken BBQ'},'P007':{name:'Ham Mushroom Six Cheese'},'P008':{name:'Premium Grilled Bulgogi'},'P009':{name:'Six Cheese'},'P010':{name:'Spicy Italian'},'P011':{name:'THIN Shrimp Alfredo'},'P012':{name:'Margherita'},'P013':{name:'Pepperoni'},'P014':{name:'Hawaiian'},'P015':{name:'Garden Special'},noPizzaTitle:'Không chọn pizza',noPizzaStrong:'Đặt không có pizza',noPizzaDesc:'Cũng có thể chỉ gọi món ăn kèm và đồ uống.'},
    nav:{home:'Về đầu',previous:'Trước',next:'Tiếp'},
    phone:{title:'Nhập số điện thoại',subtitle:'010 được cố định. Vui lòng nhập 8 số còn lại.',clear:'Xóa tất cả',orderNumber:'Mã đơn hàng (4 số cuối điện thoại):',invalid:'Vui lòng nhập chính xác 8 số cuối.',next:'Chọn phương thức thanh toán'},
    done:{title:'Đơn hàng đã được tiếp nhận',orderLabel:'Mã đơn hàng · 4 số cuối điện thoại',paymentRequired:'Vui lòng thanh toán bằng {payment} tại quầy',paymentGuide:'Pizza sẽ bắt đầu được làm sau khi thanh toán hoàn tất.',reserveTime:'Giờ đặt trước {time}',guide:'Vui lòng kiểm tra mã đơn hàng và đến quầy.',home:'Về đầu'}
  };
window.PJ_I18N_LOCALES.vi.benefit.card.normal.sideDrinkOnlyDesc='Bạn cũng có thể chỉ gọi món ăn kèm và đồ uống.';
Object.assign(window.PJ_I18N_LOCALES.vi.benefit.card.set,{title:'Set Menu'});
Object.assign(window.PJ_I18N_LOCALES.vi.benefit.card.normal,{title:'Regular Order'});
Object.assign(window.PJ_I18N_LOCALES.vi.benefit.card.takeout,{title:'Takeout 20%'});
